//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Net;
using System.Reflection;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace SocialTargetHelpAPIClient.Models
{
	/// <summary>
	/// Database       : social_target_help
	/// Data Source    : tcp://192.168.2.179:5432
	/// Server Version : 9.5.13
	/// </summary>
	public partial class STH : LinqToDB.Data.DataConnection
	{
		public ITable<common_cs_snils_validation_statuses> common_cs_snils_validation_statuses { get { return this.GetTable<common_cs_snils_validation_statuses>(); } }
		public ITable<fias_cd_address_objects>             fias_cd_address_objects             { get { return this.GetTable<fias_cd_address_objects>(); } }
		public ITable<fsin_cd_chronic_diseases>            fsin_cd_chronic_diseases            { get { return this.GetTable<fsin_cd_chronic_diseases>(); } }
		public ITable<fsin_cd_deals>                       fsin_cd_deals                       { get { return this.GetTable<fsin_cd_deals>(); } }
		public ITable<fsin_cd_events>                      fsin_cd_events                      { get { return this.GetTable<fsin_cd_events>(); } }
		public ITable<fsin_cd_exemption_categories>        fsin_cd_exemption_categories        { get { return this.GetTable<fsin_cd_exemption_categories>(); } }
		public ITable<fsin_cd_exemption_category_msp>      fsin_cd_exemption_category_msp      { get { return this.GetTable<fsin_cd_exemption_category_msp>(); } }
		public ITable<fsin_cd_family>                      fsin_cd_family                      { get { return this.GetTable<fsin_cd_family>(); } }
		public ITable<fsin_cd_msp>                         fsin_cd_msp                         { get { return this.GetTable<fsin_cd_msp>(); } }
		public ITable<fsin_cd_org_oktmo>                   fsin_cd_org_oktmo                   { get { return this.GetTable<fsin_cd_org_oktmo>(); } }
		public ITable<fsin_cd_other_documents>             fsin_cd_other_documents             { get { return this.GetTable<fsin_cd_other_documents>(); } }
		public ITable<fsin_cd_professions>                 fsin_cd_professions                 { get { return this.GetTable<fsin_cd_professions>(); } }
		public ITable<fsin_cd_realty>                      fsin_cd_realty                      { get { return this.GetTable<fsin_cd_realty>(); } }
		public ITable<fsin_cd_result>                      fsin_cd_result                      { get { return this.GetTable<fsin_cd_result>(); } }
		public ITable<fsin_cs_disabilities>                fsin_cs_disabilities                { get { return this.GetTable<fsin_cs_disabilities>(); } }
		public ITable<fsin_cs_educations>                  fsin_cs_educations                  { get { return this.GetTable<fsin_cs_educations>(); } }
		public ITable<fsin_cs_events>                      fsin_cs_events                      { get { return this.GetTable<fsin_cs_events>(); } }
		public ITable<fsin_cs_exemption_categories>        fsin_cs_exemption_categories        { get { return this.GetTable<fsin_cs_exemption_categories>(); } }
		public ITable<fsin_cs_msp_org>                     fsin_cs_msp_org                     { get { return this.GetTable<fsin_cs_msp_org>(); } }
		public ITable<fsin_cs_profession_documents>        fsin_cs_profession_documents        { get { return this.GetTable<fsin_cs_profession_documents>(); } }
		public ITable<fsin_cs_punishment_types>            fsin_cs_punishment_types            { get { return this.GetTable<fsin_cs_punishment_types>(); } }
		public ITable<fsin_cs_reason>                      fsin_cs_reason                      { get { return this.GetTable<fsin_cs_reason>(); } }
		public ITable<fsin_cs_result>                      fsin_cs_result                      { get { return this.GetTable<fsin_cs_result>(); } }
		public ITable<fsin_cs_social_statuses>             fsin_cs_social_statuses             { get { return this.GetTable<fsin_cs_social_statuses>(); } }
		public ITable<fsin_cs_status>                      fsin_cs_status                      { get { return this.GetTable<fsin_cs_status>(); } }
		public ITable<fsin_cs_territory>                   fsin_cs_territory                   { get { return this.GetTable<fsin_cs_territory>(); } }
		public ITable<fsin_cs_test_timer>                  fsin_cs_test_timer                  { get { return this.GetTable<fsin_cs_test_timer>(); } }
		public ITable<fsin_cs_types>                       fsin_cs_types                       { get { return this.GetTable<fsin_cs_types>(); } }
		public ITable<msz_cd_parent_suppliers>             msz_cd_parent_suppliers             { get { return this.GetTable<msz_cd_parent_suppliers>(); } }
		public ITable<msz_cs_fed_msz>                      msz_cs_fed_msz                      { get { return this.GetTable<msz_cs_fed_msz>(); } }
		public ITable<msz_cs_local_msz>                    msz_cs_local_msz                    { get { return this.GetTable<msz_cs_local_msz>(); } }
		public ITable<poor_cs_house_type>                  poor_cs_house_type                  { get { return this.GetTable<poor_cs_house_type>(); } }
		public ITable<public_BaseTreeNode>                 public_BaseTreeNode                 { get { return this.GetTable<public_BaseTreeNode>(); } }
		public ITable<public_cd_persons>                   public_cd_persons                   { get { return this.GetTable<public_cd_persons>(); } }
		public ITable<public_cd_post_addresses>            public_cd_post_addresses            { get { return this.GetTable<public_cd_post_addresses>(); } }
		public ITable<public_cs_bank_filials>              public_cs_bank_filials              { get { return this.GetTable<public_cs_bank_filials>(); } }
		public ITable<public_cs_bank_types>                public_cs_bank_types                { get { return this.GetTable<public_cs_bank_types>(); } }
		public ITable<public_cs_banks>                     public_cs_banks                     { get { return this.GetTable<public_cs_banks>(); } }
		public ITable<public_cs_boss_posts>                public_cs_boss_posts                { get { return this.GetTable<public_cs_boss_posts>(); } }
		public ITable<public_cs_departments>               public_cs_departments               { get { return this.GetTable<public_cs_departments>(); } }
		public ITable<public_cs_document_issues_orgs>      public_cs_document_issues_orgs      { get { return this.GetTable<public_cs_document_issues_orgs>(); } }
		public ITable<public_cs_document_type_groups>      public_cs_document_type_groups      { get { return this.GetTable<public_cs_document_type_groups>(); } }
		public ITable<public_cs_document_types>            public_cs_document_types            { get { return this.GetTable<public_cs_document_types>(); } }
		public ITable<public_cs_house_type>                public_cs_house_type                { get { return this.GetTable<public_cs_house_type>(); } }
		public ITable<public_cs_martial_status>            public_cs_martial_status            { get { return this.GetTable<public_cs_martial_status>(); } }
		public ITable<public_cs_organizations>             public_cs_organizations             { get { return this.GetTable<public_cs_organizations>(); } }
		public ITable<public_cs_sex>                       public_cs_sex                       { get { return this.GetTable<public_cs_sex>(); } }
		public ITable<public_cs_subsystems>                public_cs_subsystems                { get { return this.GetTable<public_cs_subsystems>(); } }
		public ITable<public_XPObjectType>                 public_XPObjectType                 { get { return this.GetTable<public_XPObjectType>(); } }
		public ITable<subsidy_cs_family_relations>         subsidy_cs_family_relations         { get { return this.GetTable<subsidy_cs_family_relations>(); } }
		public ITable<subsidy_cs_payment_methods>          subsidy_cs_payment_methods          { get { return this.GetTable<subsidy_cs_payment_methods>(); } }

		public void InitMappingSchema()
		{
		}

		public STH()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public STH(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext();

		#region Table Functions

		#region get_non_provide_msp

		[Sql.TableFunction(Schema="fsin", Name="get_non_provide_msp")]
		public ITable<get_non_provide_mspResult> get_non_provide_msp(string _c_address_oktmo, object _local_msz)
		{
			return this.GetTable<get_non_provide_mspResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				_c_address_oktmo,
				_local_msz);
		}

		public partial class get_non_provide_mspResult
		{
			public int?   id       { get; set; }
			public string msp_name { get; set; }
		}

		#endregion

		#endregion
	}

	[Table(Schema="common", Name="cs_snils_validation_statuses")]
	public partial class common_cs_snils_validation_statuses
	{
		[PrimaryKey, Identity] public int    id      { get; set; } // integer
		[Column,     Nullable] public string c_title { get; set; } // character varying(255)
		[Column,     Nullable] public string c_alias { get; set; } // character varying(50)
	}

	[Table(Schema="fias", Name="cd_address_objects")]
	public partial class fias_cd_address_objects
	{
		[PrimaryKey, NotNull    ] public Guid   aoid                 { get; set; } // uuid
		[Column,     NotNull    ] public Guid   aoguid               { get; set; } // uuid
		[Column,        Nullable] public string formalname           { get; set; } // character varying(120)
		[Column,        Nullable] public string regioncode           { get; set; } // character varying(2)
		[Column,        Nullable] public char?  autocode             { get; set; } // character varying(1)
		[Column,        Nullable] public string areacode             { get; set; } // character varying(3)
		[Column,        Nullable] public string citycode             { get; set; } // character varying(3)
		[Column,        Nullable] public string ctarcode             { get; set; } // character varying(3)
		[Column,        Nullable] public string placecode            { get; set; } // character varying(3)
		[Column,        Nullable] public string plancode             { get; set; } // character varying(4)
		[Column,        Nullable] public string streetcode           { get; set; } // character varying(4)
		[Column,        Nullable] public string extrcode             { get; set; } // character varying(4)
		[Column,        Nullable] public string sextcode             { get; set; } // character varying(3)
		[Column,        Nullable] public string offname              { get; set; } // character varying(120)
		[Column,        Nullable] public string postalcode           { get; set; } // character varying(6)
		[Column,        Nullable] public string ifnsfl               { get; set; } // character varying(4)
		[Column,        Nullable] public string terrifnsfl           { get; set; } // character varying(4)
		[Column,        Nullable] public string ifnsul               { get; set; } // character varying(4)
		[Column,        Nullable] public string terrifnsul           { get; set; } // character varying(4)
		[Column,        Nullable] public string okato                { get; set; } // character varying(11)
		[Column,        Nullable] public string oktmo                { get; set; } // character varying(11)
		[Column,        Nullable] public object updatedate           { get; set; } // date
		[Column,        Nullable] public string shortname            { get; set; } // character varying(10)
		[Column,     NotNull    ] public short  aolevel              { get; set; } // smallint
		[Column,        Nullable] public Guid?  parentguid           { get; set; } // uuid
		[Column,        Nullable] public Guid?  previd               { get; set; } // uuid
		[Column,        Nullable] public Guid?  nextid               { get; set; } // uuid
		[Column,        Nullable] public string code                 { get; set; } // character varying(17)
		[Column,        Nullable] public string plaincode            { get; set; } // character varying(15)
		[Column,     NotNull    ] public bool   actstatus            { get; set; } // boolean
		[Column,     NotNull    ] public bool   livestatus           { get; set; } // boolean
		[Column,     NotNull    ] public short  centstatus           { get; set; } // smallint
		[Column,     NotNull    ] public short  operstatus           { get; set; } // smallint
		[Column,     NotNull    ] public short  currstatus           { get; set; } // smallint
		[Column,     NotNull    ] public object startdate            { get; set; } // date
		[Column,     NotNull    ] public object enddate              { get; set; } // date
		[Column,        Nullable] public Guid?  normdoc              { get; set; } // uuid
		[Column,        Nullable] public string cadnum               { get; set; } // character varying(100)
		[Column,     NotNull    ] public short  divtype              { get; set; } // smallint
		[Column,        Nullable] public string formalname_lowercase { get; set; } // character varying(120)
		[Column,        Nullable] public string fullname             { get; set; } // character varying(256)
	}

	[Table(Schema="fsin", Name="cd_chronic_diseases")]
	public partial class fsin_cd_chronic_diseases
	{
		[PrimaryKey, Identity   ] public int    id        { get; set; } // integer
		[Column,     NotNull    ] public string c_disease { get; set; } // character varying(255)
		[Column,        Nullable] public int?   f_cd_deal { get; set; } // integer
		[Column,        Nullable] public string c_user    { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// cd_chronic_diseases_f_cd_deal_fkey
		/// </summary>
		[Association(ThisKey="f_cd_deal", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_chronic_diseases_f_cd_deal_fkey")]
		public fsin_cd_deals cdchronicdiseasesfcddealfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_deals")]
	public partial class fsin_cd_deals
	{
		[PrimaryKey, Identity   ] public int      id                        { get; set; } // integer
		[Column,     NotNull    ] public string   c_series                  { get; set; } // character varying(2)
		[Column,     NotNull    ] public string   c_number                  { get; set; } // character varying(6)
		[Column,     NotNull    ] public object   d_date_of_issue           { get; set; } // date
		[Column,     NotNull    ] public string   c_issued_by               { get; set; } // character varying(255)
		[Column,        Nullable] public string   c_psy_char                { get; set; } // text
		[Column,        Nullable] public int?     f_cs_education            { get; set; } // integer
		[Column,        Nullable] public int?     f_cs_disability           { get; set; } // integer
		[Column,        Nullable] public int?     f_cs_social_status        { get; set; } // integer
		[Column,     NotNull    ] public int      f_cd_persons              { get; set; } // integer
		[Column,     NotNull    ] public string   c_address                 { get; set; } // character varying(512)
		[Column,        Nullable] public Guid?    f_address_fias_code       { get; set; } // uuid
		[Column,        Nullable] public string   c_address_house           { get; set; } // character varying(20)
		[Column,        Nullable] public string   c_address_corpus          { get; set; } // character varying(20)
		[Column,        Nullable] public string   c_address_flat            { get; set; } // character varying(20)
		[Column,        Nullable] public string   c_address_region          { get; set; } // character varying(64)
		[Column,        Nullable] public string   c_address_district        { get; set; } // character varying(64)
		[Column,        Nullable] public string   c_address_city            { get; set; } // character varying(64)
		[Column,        Nullable] public string   c_address_settlement      { get; set; } // character varying(64)
		[Column,        Nullable] public string   c_address_street          { get; set; } // character varying(64)
		[Column,        Nullable] public Guid?    f_house_fias_code         { get; set; } // uuid
		[Column,     NotNull    ] public int      n_deal_number             { get; set; } // integer
		[Column,     NotNull    ] public object   d_date_of_create_deal     { get; set; } // date
		[Column,        Nullable] public string   c_address_oktmo           { get; set; } // character varying(11)
		[Column,        Nullable] public int?     f_cs_status               { get; set; } // integer
		[Column,        Nullable] public decimal? n_money_for_transit       { get; set; } // numeric(10,2)
		[Column,        Nullable] public decimal? n_money_for_eat           { get; set; } // numeric(10,2)
		[Column,        Nullable] public decimal? n_money_for_another       { get; set; } // numeric(10,2)
		[Column,        Nullable] public object   d_conviction_date         { get; set; } // date
		[Column,        Nullable] public string   c_court_name              { get; set; } // character varying(500)
		[Column,        Nullable] public string   c_other                   { get; set; } // character varying(500)
		[Column,        Nullable] public int?     c_punishment_period_year  { get; set; } // integer
		[Column,        Nullable] public int?     c_punishment_period_month { get; set; } // integer
		[Column,        Nullable] public int?     f_punishment_type         { get; set; } // integer
		[Column,     NotNull    ] public bool     b_done                    { get; set; } // boolean
		[Column,        Nullable] public object   d_date_of_arrival         { get; set; } // date
		[Column,        Nullable] public int?     f_marital_status          { get; set; } // integer
		[Column,        Nullable] public object   d_ipra_date               { get; set; } // date
		[Column,        Nullable] public string   c_user                    { get; set; } // character varying(255)
		[Column,        Nullable] public string   c_post                    { get; set; } // character varying(255)
		[Column,        Nullable] public string   c_base                    { get; set; } // character varying(255)
		[Column,        Nullable] public string   c_reason                  { get; set; } // character varying(255)
		[Column,        Nullable] public string   c_archive_date            { get; set; } // character varying(50)
		[Column,        Nullable] public string   c_criminal_record         { get; set; } // text

		#region Associations

		/// <summary>
		/// cd_deals_f_cd_persons_fkey
		/// </summary>
		[Association(ThisKey="f_cd_persons", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_deals_f_cd_persons_fkey")]
		public public_cd_persons cddealsfcdpersonsfkey { get; set; }

		/// <summary>
		/// cd_deals_f_cs_disability_fkey
		/// </summary>
		[Association(ThisKey="f_cs_disability", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_deals_f_cs_disability_fkey")]
		public fsin_cs_disabilities cddealsfcsdisabilityfkey { get; set; }

		/// <summary>
		/// cd_deals_f_cs_education_fkey
		/// </summary>
		[Association(ThisKey="f_cs_education", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_deals_f_cs_education_fkey")]
		public fsin_cs_educations cddealsfcseducationfkey { get; set; }

		/// <summary>
		/// cd_deals_f_cs_punishment_types_fkey
		/// </summary>
		[Association(ThisKey="f_punishment_type", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_deals_f_cs_punishment_types_fkey")]
		public fsin_cs_punishment_types cddealsfcspunishmenttypesfkey { get; set; }

		/// <summary>
		/// cd_deals_f_cs_social_status_fkey
		/// </summary>
		[Association(ThisKey="f_cs_social_status", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_deals_f_cs_social_status_fkey")]
		public fsin_cs_social_statuses cddealsfcssocialstatusfkey { get; set; }

		/// <summary>
		/// cd_deals_f_cs_status_fkey
		/// </summary>
		[Association(ThisKey="f_cs_status", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_deals_f_cs_status_fkey")]
		public fsin_cs_status cddealsfcsstatusfkey { get; set; }

		/// <summary>
		/// cd_deals_f_marital_status_fkey
		/// </summary>
		[Association(ThisKey="f_marital_status", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_deals_f_marital_status_fkey")]
		public public_cs_martial_status cddealsfmaritalstatusfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_events")]
	public partial class fsin_cd_events
	{
		[PrimaryKey, NotNull    ] public Guid   id                { get; set; } // uuid
		[Column,        Nullable] public int?   f_cs_events       { get; set; } // integer
		[Column,     NotNull    ] public Guid   f_cd_msp          { get; set; } // uuid
		[Column,     NotNull    ] public bool   b_done            { get; set; } // boolean
		[Column,     NotNull    ] public object d_start_date      { get; set; } // date
		[Column,        Nullable] public object d_end_date        { get; set; } // date
		[Column,        Nullable] public string c_user_policy_org { get; set; } // character varying(255)
		[Column,        Nullable] public string c_user_policy     { get; set; } // character varying(255)
		[Column,        Nullable] public string c_user            { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// FK_fsin_cd_events_id_3690F5C9
		/// </summary>
		[Association(ThisKey="id", OtherKey="id", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="FK_fsin_cd_events_id_3690F5C9")]
		public public_BaseTreeNode BaseTreeNode { get; set; }

		/// <summary>
		/// cd_events_f_cd_msp_fkey
		/// </summary>
		[Association(ThisKey="f_cd_msp", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_events_f_cd_msp_fkey")]
		public fsin_cd_msp cdeventsfcdmspfkey { get; set; }

		/// <summary>
		/// cd_events_f_cs_events_fkey
		/// </summary>
		[Association(ThisKey="f_cs_events", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_events_f_cs_events_fkey")]
		public fsin_cs_events cdeventsfcseventsfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_exemption_categories")]
	public partial class fsin_cd_exemption_categories
	{
		[PrimaryKey, Identity   ] public int  id                      { get; set; } // integer
		[Column,     NotNull    ] public int  f_cd_deal               { get; set; } // integer
		[Column,        Nullable] public int? f_cs_exemption_category { get; set; } // integer

		#region Associations

		/// <summary>
		/// cd_exemption_categories_f_cd_deal_fkey
		/// </summary>
		[Association(ThisKey="f_cd_deal", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_exemption_categories_f_cd_deal_fkey")]
		public fsin_cd_deals cdexemptioncategoriesfcddealfkey { get; set; }

		/// <summary>
		/// cd_exemption_categories_f_cs_exemption_categories_fkey
		/// </summary>
		[Association(ThisKey="f_cs_exemption_category", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_exemption_categories_f_cs_exemption_categories_fkey")]
		public fsin_cs_exemption_categories cdexemptioncategoriesfcsexemptioncategoriesfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_exemption_category_msp")]
	public partial class fsin_cd_exemption_category_msp
	{
		[PrimaryKey, Identity] public int  id                        { get; set; } // integer
		[Column,     Nullable] public int? f_cs_exemption_categories { get; set; } // integer
		[Column,     Nullable] public int? f_cs_local_msz            { get; set; } // integer

		#region Associations

		/// <summary>
		/// cd_exemption_category_events_f_cs_exemption_categories_fkey
		/// </summary>
		[Association(ThisKey="f_cs_exemption_categories", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_exemption_category_events_f_cs_exemption_categories_fkey")]
		public fsin_cs_exemption_categories cdexemptioncategoryeventsfcsexemptioncategoriesfkey { get; set; }

		/// <summary>
		/// cd_exemption_category_msp_f_cs_local_msz_fkey
		/// </summary>
		[Association(ThisKey="f_cs_local_msz", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_exemption_category_msp_f_cs_local_msz_fkey")]
		public msz_cs_local_msz cdexemptioncategorymspfcslocalmszfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_family")]
	public partial class fsin_cd_family
	{
		[Column,     Nullable] public string c_fio      { get; set; } // character varying(500)
		[Column,     Nullable] public int?   f_relation { get; set; } // integer
		[Column,     Nullable] public int?   f_cd_deal  { get; set; } // integer
		[PrimaryKey, Identity] public int    id         { get; set; } // integer
		[Column,     Nullable] public string c_user     { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// cd_family_f_cd_deal_fkey
		/// </summary>
		[Association(ThisKey="f_cd_deal", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_family_f_cd_deal_fkey")]
		public fsin_cd_deals cdfamilyfcddealfkey { get; set; }

		/// <summary>
		/// cd_msp_f_cd_family_fkey
		/// </summary>
		[Association(ThisKey="f_relation", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_msp_f_cd_family_fkey")]
		public subsidy_cs_family_relations cdmspfcdfamilyfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_msp")]
	public partial class fsin_cd_msp
	{
		[PrimaryKey, NotNull    ] public Guid   id             { get; set; } // uuid
		[Column,     NotNull    ] public int    f_cd_deals     { get; set; } // integer
		[Column,        Nullable] public int?   f_cs_local_msz { get; set; } // integer
		[Column,     NotNull    ] public bool   b_done         { get; set; } // boolean
		[Column,        Nullable] public string c_user         { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// cd_msp_id_fkey
		/// </summary>
		[Association(ThisKey="id", OtherKey="id", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="cd_msp_id_fkey")]
		public public_BaseTreeNode BaseTreeNode { get; set; }

		/// <summary>
		/// cd_msp_f_cd_deals_fkey
		/// </summary>
		[Association(ThisKey="f_cd_deals", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_msp_f_cd_deals_fkey")]
		public fsin_cd_deals cdmspfcddealsfkey { get; set; }

		/// <summary>
		/// cd_msp_f_cs_local_msz_fkey
		/// </summary>
		[Association(ThisKey="f_cs_local_msz", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_msp_f_cs_local_msz_fkey")]
		public msz_cs_local_msz cdmspfcslocalmszfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_org_oktmo")]
	public partial class fsin_cd_org_oktmo
	{
		[PrimaryKey, Identity   ] public int    id      { get; set; } // integer
		[Column,        Nullable] public string c_oktmo { get; set; } // character varying(50)
		[Column,     NotNull    ] public int    f_org   { get; set; } // integer

		#region Associations

		/// <summary>
		/// cd_org_oktmo_cs_oganizations_fkey
		/// </summary>
		[Association(ThisKey="f_org", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_org_oktmo_cs_oganizations_fkey")]
		public public_cs_organizations cdorgoktmocsoganizationsfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_other_documents")]
	public partial class fsin_cd_other_documents
	{
		[PrimaryKey, Identity   ] public int    id                       { get; set; } // integer
		[Column,     NotNull    ] public string c_series                 { get; set; } // character varying
		[Column,     NotNull    ] public string c_number                 { get; set; } // character varying
		[Column,     NotNull    ] public object d_date_of_issue          { get; set; } // date
		[Column,     NotNull    ] public int    f_cd_deal                { get; set; } // integer
		[Column,        Nullable] public int?   f_cs_document_type       { get; set; } // integer
		[Column,        Nullable] public int?   f_cs_document_issues_org { get; set; } // integer
		[Column,        Nullable] public string c_user                   { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// cd_other_documents_f_cd_deal_fkey
		/// </summary>
		[Association(ThisKey="f_cd_deal", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_other_documents_f_cd_deal_fkey")]
		public fsin_cd_deals cdotherdocumentsfcddealfkey { get; set; }

		/// <summary>
		/// cd_other_documents_f_cs_document_issues_org_fkey
		/// </summary>
		[Association(ThisKey="f_cs_document_issues_org", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_other_documents_f_cs_document_issues_org_fkey")]
		public public_cs_document_issues_orgs cdotherdocumentsfcsdocumentissuesorgfkey { get; set; }

		/// <summary>
		/// cd_other_documents_f_cs_document_type_fkey
		/// </summary>
		[Association(ThisKey="f_cs_document_type", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_other_documents_f_cs_document_type_fkey")]
		public public_cs_document_types cdotherdocumentsfcsdocumenttypefkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_professions")]
	public partial class fsin_cd_professions
	{
		[PrimaryKey, Identity   ] public int    id                       { get; set; } // integer
		[Column,     NotNull    ] public string c_specialty              { get; set; } // character varying(255)
		[Column,     NotNull    ] public string c_qualification          { get; set; } // character varying(255)
		[Column,        Nullable] public int?   f_cs_profession_document { get; set; } // integer
		[Column,     NotNull    ] public object d_date_of_issue          { get; set; } // date
		[Column,     NotNull    ] public string c_issued_by              { get; set; } // character varying(255)
		[Column,     NotNull    ] public int    f_cd_deal                { get; set; } // integer
		[Column,        Nullable] public string c_user                   { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// cd_professions_f_cd_deal_fkey
		/// </summary>
		[Association(ThisKey="f_cd_deal", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_professions_f_cd_deal_fkey")]
		public fsin_cd_deals cdprofessionsfcddealfkey { get; set; }

		/// <summary>
		/// cd_professions_f_cs_profession_document_fkey
		/// </summary>
		[Association(ThisKey="f_cs_profession_document", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_professions_f_cs_profession_document_fkey")]
		public fsin_cs_profession_documents cdprofessionsfcsprofessiondocumentfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_realty")]
	public partial class fsin_cd_realty
	{
		[PrimaryKey, Identity] public int    id        { get; set; } // integer
		[Column,     Nullable] public int?   f_cs_type { get; set; } // integer
		[Column,     Nullable] public string c_address { get; set; } // character varying(500)
		[Column,     Nullable] public int?   f_cd_deal { get; set; } // integer
		[Column,     Nullable] public string c_user    { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// cd_realty_f_cd_deal_fkey
		/// </summary>
		[Association(ThisKey="f_cd_deal", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_realty_f_cd_deal_fkey")]
		public fsin_cd_deals cdrealtyfcddealfkey { get; set; }

		/// <summary>
		/// cd_realty_f_cs_type_fkey
		/// </summary>
		[Association(ThisKey="f_cs_type", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_realty_f_cs_type_fkey")]
		public public_cs_house_type cdrealtyfcstypefkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cd_result")]
	public partial class fsin_cd_result
	{
		[PrimaryKey, NotNull    ] public Guid   id           { get; set; } // uuid
		[Column,        Nullable] public int?   f_cs_results { get; set; } // integer
		[Column,     NotNull    ] public Guid   f_cd_events  { get; set; } // uuid
		[Column,        Nullable] public string c_result     { get; set; } // character varying
		[Column,        Nullable] public string c_user       { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// FK_fsin_cd_result_id_A156AD10
		/// </summary>
		[Association(ThisKey="id", OtherKey="id", CanBeNull=false, Relationship=Relationship.OneToOne, KeyName="FK_fsin_cd_result_id_A156AD10")]
		public public_BaseTreeNode BaseTreeNode { get; set; }

		/// <summary>
		/// cd_result_f_cd_events_fkey
		/// </summary>
		[Association(ThisKey="f_cd_events", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_result_f_cd_events_fkey")]
		public fsin_cd_events cdresultfcdeventsfkey { get; set; }

		/// <summary>
		/// cd_result_f_cs_results_fkey
		/// </summary>
		[Association(ThisKey="f_cs_results", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_result_f_cs_results_fkey")]
		public fsin_cs_result cdresultfcsresultsfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cs_disabilities")]
	public partial class fsin_cs_disabilities
	{
		[PrimaryKey, Identity] public int    id         { get; set; } // integer
		[Column,     NotNull ] public string c_category { get; set; } // character varying(255)
	}

	[Table(Schema="fsin", Name="cs_educations")]
	public partial class fsin_cs_educations
	{
		[PrimaryKey, Identity] public int    id          { get; set; } // integer
		[Column,     Nullable] public string c_education { get; set; } // character varying(255)
	}

	[Table(Schema="fsin", Name="cs_events")]
	public partial class fsin_cs_events
	{
		[PrimaryKey, Identity   ] public int    id             { get; set; } // integer
		[Column,     NotNull    ] public string c_name         { get; set; } // character varying(255)
		[Column,        Nullable] public int?   f_cs_local_msz { get; set; } // integer

		#region Associations

		/// <summary>
		/// cs_events_fkey_f_cs_local_msz
		/// </summary>
		[Association(ThisKey="f_cs_local_msz", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cs_events_fkey_f_cs_local_msz")]
		public msz_cs_local_msz cseventsfkeyfcslocalmsz { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cs_exemption_categories")]
	public partial class fsin_cs_exemption_categories
	{
		[PrimaryKey, Identity   ] public int    id         { get; set; } // integer
		[Column,     NotNull    ] public string c_category { get; set; } // character varying(255)
		[Column,        Nullable] public string c_alias    { get; set; } // character varying(50)
	}

	[Table(Schema="fsin", Name="cs_msp_org")]
	public partial class fsin_cs_msp_org
	{
		[PrimaryKey, Identity] public int  id          { get; set; } // integer
		[Column,     Nullable] public int? f_local_msz { get; set; } // integer
		[Column,     Nullable] public int? f_org       { get; set; } // integer

		#region Associations

		/// <summary>
		/// cs_msp_org_f_cd_deals_fkey
		/// </summary>
		[Association(ThisKey="f_org", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cs_msp_org_f_cd_deals_fkey")]
		public public_cs_organizations csmsporgfcddealsfkey { get; set; }

		/// <summary>
		/// cs_msp_org_f_local_msz_fkey
		/// </summary>
		[Association(ThisKey="f_local_msz", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cs_msp_org_f_local_msz_fkey")]
		public msz_cs_local_msz csmsporgflocalmszfkey { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cs_profession_documents")]
	public partial class fsin_cs_profession_documents
	{
		[PrimaryKey, Identity] public int    id     { get; set; } // integer
		[Column,     NotNull ] public string c_type { get; set; } // character varying(255)
	}

	[Table(Schema="fsin", Name="cs_punishment_types")]
	public partial class fsin_cs_punishment_types
	{
		[PrimaryKey, Identity] public int    id                  { get; set; } // integer
		[Column,     Nullable] public string c_f_punishment_type { get; set; } // character varying(255)
	}

	[Table(Schema="fsin", Name="cs_reason")]
	public partial class fsin_cs_reason
	{
		[PrimaryKey, Identity] public int    id       { get; set; } // integer
		[Column,     Nullable] public string c_reason { get; set; } // character varying(255)
		[Column,     Nullable] public string c_alias  { get; set; } // character varying(255)
	}

	[Table(Schema="fsin", Name="cs_result")]
	public partial class fsin_cs_result
	{
		[PrimaryKey, Identity] public int    id             { get; set; } // integer
		[Column,     Nullable] public string c_name         { get; set; } // character varying(255)
		[Column,     Nullable] public int?   f_cs_types     { get; set; } // integer
		[Column,     Nullable] public int?   f_cs_local_msz { get; set; } // integer

		#region Associations

		/// <summary>
		/// cs_result_fkey_f_cs_local_msz
		/// </summary>
		[Association(ThisKey="f_cs_local_msz", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cs_result_fkey_f_cs_local_msz")]
		public msz_cs_local_msz csresultfkeyfcslocalmsz { get; set; }

		/// <summary>
		/// cs_result_fkey_f_cs_types
		/// </summary>
		[Association(ThisKey="f_cs_types", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cs_result_fkey_f_cs_types")]
		public fsin_cs_types csresultfkeyfcstype { get; set; }

		#endregion
	}

	[Table(Schema="fsin", Name="cs_social_statuses")]
	public partial class fsin_cs_social_statuses
	{
		[PrimaryKey, Identity] public int    id       { get; set; } // integer
		[Column,     NotNull ] public string c_status { get; set; } // character varying(255)
	}

	[Table(Schema="fsin", Name="cs_status")]
	public partial class fsin_cs_status
	{
		[PrimaryKey, Identity] public int    id       { get; set; } // integer
		[Column,     NotNull ] public string c_status { get; set; } // character varying(50)
		[Column,     NotNull ] public string c_alias  { get; set; } // character varying(50)
	}

	[Table(Schema="fsin", Name="cs_territory")]
	public partial class fsin_cs_territory
	{
		[PrimaryKey, Identity] public int    id                  { get; set; } // integer
		[Column,     Nullable] public string c_territory_name    { get; set; } // character varying(255)
		[Column,     Nullable] public string c_territory_address { get; set; } // character varying(255)
	}

	[Table(Schema="fsin", Name="cs_test_timer")]
	public partial class fsin_cs_test_timer
	{
		[Identity          ] public int    id     { get; set; } // integer
		[Column,   Nullable] public object d_date { get; set; } // timestamp (6) without time zone
	}

	[Table(Schema="fsin", Name="cs_types")]
	public partial class fsin_cs_types
	{
		[PrimaryKey, Identity] public int    id          { get; set; } // integer
		[Column,     Nullable] public string c_type_name { get; set; } // character varying(200)
		[Column,     Nullable] public string c_type      { get; set; } // character varying(150)
	}

	[Table(Schema="msz", Name="cd_parent_suppliers")]
	public partial class msz_cd_parent_suppliers
	{
		[PrimaryKey, Identity] public int    id       { get; set; } // integer
		[Column,     Nullable] public string c_name   { get; set; } // character varying(500)
		[Column,     Nullable] public string c_region { get; set; } // character varying(3)
		[Column,     Nullable] public string c_code   { get; set; } // character varying(11)
	}

	[Table(Schema="msz", Name="cs_fed_msz")]
	public partial class msz_cs_fed_msz
	{
		[PrimaryKey, Identity] public int    id     { get; set; } // integer
		[Column,     Nullable] public string c_name { get; set; } // character varying(500)
		[Column,     Nullable] public string c_code { get; set; } // character varying(6)
	}

	[Table(Schema="msz", Name="cs_local_msz")]
	public partial class msz_cs_local_msz
	{
		[PrimaryKey, Identity   ] public int    id                 { get; set; } // integer
		[Column,     NotNull    ] public int    f_fed_msz          { get; set; } // integer
		[Column,     NotNull    ] public string c_id_msz_local     { get; set; } // character varying(50)
		[Column,     NotNull    ] public int    f_parent_supplier  { get; set; } // integer
		[Column,        Nullable] public string c_code             { get; set; } // character varying(20)
		[Column,        Nullable] public string c_kbk              { get; set; } // character varying(20)
		[Column,        Nullable] public string c_estimation       { get; set; } // character varying(500)
		[Column,        Nullable] public string c_title            { get; set; } // character varying(2000)
		[Column,        Nullable] public object d_enact            { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public object d_expiration       { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string c_periodicity_code { get; set; } // character varying(2)
		[Column,     NotNull    ] public int    f_subsystem        { get; set; } // integer
		[Column,        Nullable] public string c_alias            { get; set; } // character varying(50)

		#region Associations

		/// <summary>
		/// cs_local_msz_fkey_f_fed_msz
		/// </summary>
		[Association(ThisKey="f_fed_msz", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_local_msz_fkey_f_fed_msz")]
		public msz_cs_fed_msz cslocalfkeyffed { get; set; }

		/// <summary>
		/// cs_local_msz_fkey_f_parent_supplier
		/// </summary>
		[Association(ThisKey="f_parent_supplier", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_local_msz_fkey_f_parent_supplier")]
		public msz_cd_parent_suppliers cslocalfkeyfparentsupplier { get; set; }

		/// <summary>
		/// cs_local_msz_fkey_f_subsystem
		/// </summary>
		[Association(ThisKey="f_subsystem", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_local_msz_fkey_f_subsystem")]
		public public_cs_subsystems cslocalfkeyfsubsystem { get; set; }

		#endregion
	}

	[Table(Schema="poor", Name="cs_house_type")]
	public partial class poor_cs_house_type
	{
		[PrimaryKey, NotNull] public Guid   id     { get; set; } // uuid
		[Column,     NotNull] public string c_name { get; set; } // character varying(300)
	}

	[Table(Schema="public", Name="BaseTreeNode")]
	public partial class public_BaseTreeNode
	{
		[PrimaryKey, NotNull    ] public Guid   id                  { get; set; } // uuid
		[Column,        Nullable] public string Name                { get; set; } // character varying(100)
		[Column,        Nullable] public int?   OptimisticLockField { get; set; } // integer
		[Column,        Nullable] public int?   GCRecord            { get; set; } // integer
		[Column,        Nullable] public int?   ObjectType          { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_BaseTreeNode_ObjectType
		/// </summary>
		[Association(ThisKey="ObjectType", OtherKey="OID", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_BaseTreeNode_ObjectType")]
		public public_XPObjectType FK_BaseTreeNode_ObjectType { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cd_persons")]
	public partial class public_cd_persons
	{
		[Column,     NotNull    ] public string c_surname                       { get; set; } // character varying(64)
		[Column,     NotNull    ] public string c_first_name                    { get; set; } // character varying(64)
		[Column,        Nullable] public string c_patronymic                    { get; set; } // character varying(64)
		[Column,     NotNull    ] public object d_birthday                      { get; set; } // date
		[Column,     NotNull    ] public string c_document_seria                { get; set; } // character varying(6)
		[Column,     NotNull    ] public string c_document_number               { get; set; } // character varying(7)
		[Column,        Nullable] public string c_phone                         { get; set; } // character varying(32)
		[PrimaryKey, Identity   ] public int    id                              { get; set; } // integer
		[Column,        Nullable] public string c_inn                           { get; set; } // character varying(12)
		[Column,     NotNull    ] public string c_snils                         { get; set; } // character varying(14)
		[Column,     NotNull    ] public int    f_document_type                 { get; set; } // integer
		[Column,        Nullable] public string c_birth_place                   { get; set; } // character varying(512)
		[Column,        Nullable] public object d_date_issue                    { get; set; } // date
		[Column,        Nullable] public int?   f_issued_by                     { get; set; } // integer
		[Column,     NotNull    ] public bool   b_agreed                        { get; set; } // boolean
		[Column,     NotNull    ] public int    f_department                    { get; set; } // integer
		[Column,        Nullable] public int?   f_org                           { get; set; } // integer
		[Column,        Nullable] public Guid?  f_address_reg_fias_code         { get; set; } // uuid
		[Column,        Nullable] public string c_address_reg_house             { get; set; } // character varying(20)
		[Column,        Nullable] public string c_address_reg_corpus            { get; set; } // character varying(20)
		[Column,        Nullable] public string c_address_reg_flat              { get; set; } // character varying(20)
		[Column,        Nullable] public string c_address_reg_plain             { get; set; } // character varying(512)
		[Column,        Nullable] public string c_address_reg_region            { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_reg_district          { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_reg_city              { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_reg_settlement        { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_reg_street            { get; set; } // character varying(64)
		[Column,        Nullable] public Guid?  f_address_live_fias_code        { get; set; } // uuid
		[Column,        Nullable] public string c_address_live_house            { get; set; } // character varying(20)
		[Column,        Nullable] public string c_address_live_corpus           { get; set; } // character varying(20)
		[Column,        Nullable] public string c_address_live_flat             { get; set; } // character varying(20)
		[Column,        Nullable] public string c_address_live_plain            { get; set; } // character varying(512)
		[Column,        Nullable] public string c_address_live_region           { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_live_district         { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_live_city             { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_live_settlement       { get; set; } // character varying(64)
		[Column,        Nullable] public string c_address_live_street           { get; set; } // character varying(64)
		[Column,     NotNull    ] public bool   b_addresses_match               { get; set; } // boolean
		[Column,        Nullable] public int?   f_post_address                  { get; set; } // integer
		[Column,        Nullable] public int?   f_sex                           { get; set; } // integer
		[Column,        Nullable] public string c_citizenship                   { get; set; } // character varying(3)
		[Column,        Nullable] public string c_maidenfamilyname              { get; set; } // character varying(100)
		[Column,        Nullable] public string c_residencepermitinfo           { get; set; } // character varying(100)
		[Column,        Nullable] public int?   f_prev_org                      { get; set; } // integer
		[Column,        Nullable] public int?   imp_id                          { get; set; } // integer
		[Column,        Nullable] public string c_address_reg_kladr             { get; set; } // character varying(200)
		[Column,        Nullable] public string c_address_live_kladr            { get; set; } // character varying(200)
		[Column,        Nullable] public Guid?  f_house_fias_reg_code           { get; set; } // uuid
		[Column,        Nullable] public Guid?  f_house_fias_live_code          { get; set; } // uuid
		[Column,        Nullable] public int?   f_snils_validation_status       { get; set; } // integer
		[Column,        Nullable] public string c_snils11                       { get; set; } // character(11)
		[Column,        Nullable] public Guid?  f_snils_validation_smev_request { get; set; } // uuid
		[Column,     NotNull    ] public bool   b_dead                          { get; set; } // boolean
		[Column,        Nullable] public object d_death                         { get; set; } // date
		[Column,        Nullable] public string c_death_number                  { get; set; } // character varying(10)
		[Column,        Nullable] public object d_death_act                     { get; set; } // date
		[Column,        Nullable] public Guid?  f_fed_edv                       { get; set; } // uuid
		[Column,     NotNull    ] public bool   b_work                          { get; set; } // boolean

		#region Associations

		/// <summary>
		/// cd_persons_fkey_f_department
		/// </summary>
		[Association(ThisKey="f_department", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_department")]
		public public_cs_departments cdpersonsfkeyfdepartment { get; set; }

		/// <summary>
		/// cd_persons_fkey_f_document_type
		/// </summary>
		[Association(ThisKey="f_document_type", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_document_type")]
		public public_cs_document_types cdpersonsfkeyfdocumenttype { get; set; }

		/// <summary>
		/// cd_persons_fkey_f_issued_by
		/// </summary>
		[Association(ThisKey="f_issued_by", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_issued_by")]
		public public_cs_document_issues_orgs cdpersonsfkeyfissuedby { get; set; }

		/// <summary>
		/// cd_persons_fkey_f_org
		/// </summary>
		[Association(ThisKey="f_org", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_org")]
		public public_cs_organizations cdpersonsfkeyforg { get; set; }

		/// <summary>
		/// cd_persons_fkey_f_post_address
		/// </summary>
		[Association(ThisKey="f_post_address", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_post_address")]
		public public_cd_post_addresses cdpersonsfkeyfpostaddress { get; set; }

		/// <summary>
		/// cd_persons_fkey_f_prev_org
		/// </summary>
		[Association(ThisKey="f_prev_org", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_prev_org")]
		public public_cs_organizations cdpersonsfkeyfprevorg { get; set; }

		/// <summary>
		/// cd_persons_fkey_f_sex
		/// </summary>
		[Association(ThisKey="f_sex", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_sex")]
		public public_cs_sex cdpersonsfkeyfsex { get; set; }

		/// <summary>
		/// cd_persons_fkey_f_snils_validation_status
		/// </summary>
		[Association(ThisKey="f_snils_validation_status", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_persons_fkey_f_snils_validation_status")]
		public common_cs_snils_validation_statuses cdpersonsfkeyfsnilsvalidationstatu { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cd_post_addresses")]
	public partial class public_cd_post_addresses
	{
		[PrimaryKey, Identity] public int    id                { get; set; } // integer
		[Column,     Nullable] public Guid?  uuid_fias         { get; set; } // uuid
		[Column,     Nullable] public string c_kladr           { get; set; } // character varying(17)
		[Column,     Nullable] public string c_house_begin     { get; set; } // character varying(10)
		[Column,     Nullable] public string c_house_end       { get; set; } // character varying(10)
		[Column,     Nullable] public bool?  b_even            { get; set; } // boolean
		[Column,     Nullable] public string c_korp            { get; set; } // character varying(10)
		[Column,     Nullable] public int?   n_apartment_begin { get; set; } // integer
		[Column,     Nullable] public int?   n_apartment_end   { get; set; } // integer
		[Column,     Nullable] public string c_index           { get; set; } // character varying(10)
		[Column,     Nullable] public int?   f_filial          { get; set; } // integer
		[Column,     Nullable] public int?   n_uch             { get; set; } // integer
		[Column,     Nullable] public int?   n_day             { get; set; } // integer

		#region Associations

		/// <summary>
		/// cd_post_addresses_fkey_f_filial
		/// </summary>
		[Association(ThisKey="f_filial", OtherKey="id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_post_addresses_fkey_f_filial")]
		public public_cs_bank_filials cdpostaddressesfkeyffilial { get; set; }

		/// <summary>
		/// cd_post_addresses_fkey_f_uuid_fias
		/// </summary>
		[Association(ThisKey="uuid_fias", OtherKey="aoid", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="cd_post_addresses_fkey_f_uuid_fias")]
		public fias_cd_address_objects cdpostaddressesfkeyfuuidfia { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cs_bank_filials")]
	public partial class public_cs_bank_filials
	{
		[PrimaryKey, Identity   ] public int    id               { get; set; } // integer
		[Column,     NotNull    ] public int    f_bank           { get; set; } // integer
		[Column,     NotNull    ] public string c_name           { get; set; } // character varying(250)
		[Column,        Nullable] public string c_boss_post      { get; set; } // character varying(50)
		[Column,        Nullable] public string c_boss_fio       { get; set; } // character varying(50)
		[Column,     NotNull    ] public int    f_payment_method { get; set; } // integer
		[Column,     NotNull    ] public int    f_department     { get; set; } // integer
		[Column,        Nullable] public int?   n_post_site      { get; set; } // integer
		[Column,        Nullable] public int?   n_post_day       { get; set; } // integer
		[Column,        Nullable] public int?   imp_id           { get; set; } // integer

		#region Associations

		/// <summary>
		/// cs_bank_filial_fkey_cs_banks
		/// </summary>
		[Association(ThisKey="f_bank", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_bank_filial_fkey_cs_banks")]
		public public_cs_banks csbankfilialfkeycsbank { get; set; }

		/// <summary>
		/// cs_banks_filial_fkey_f_department
		/// </summary>
		[Association(ThisKey="f_department", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_banks_filial_fkey_f_department")]
		public public_cs_departments csbanksfilialfkeyfdepartment { get; set; }

		/// <summary>
		/// cs_banks_filial_fkey_f_payment_method
		/// </summary>
		[Association(ThisKey="f_payment_method", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_banks_filial_fkey_f_payment_method")]
		public subsidy_cs_payment_methods csbanksfilialfkeyfpaymentmethod { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cs_bank_types")]
	public partial class public_cs_bank_types
	{
		[PrimaryKey, Identity   ] public int    id      { get; set; } // integer
		[Column,     NotNull    ] public string c_name  { get; set; } // character varying(128)
		[Column,        Nullable] public string c_alias { get; set; } // character varying(128)
	}

	[Table(Schema="public", Name="cs_banks")]
	public partial class public_cs_banks
	{
		[PrimaryKey, Identity   ] public int    id                 { get; set; } // integer
		[Column,     NotNull    ] public int    f_type             { get; set; } // integer
		[Column,     NotNull    ] public string c_name             { get; set; } // character varying(250)
		[Column,        Nullable] public string c_inn              { get; set; } // character varying(10)
		[Column,        Nullable] public string c_kpp              { get; set; } // character varying(9)
		[Column,        Nullable] public string c_bik              { get; set; } // character varying(9)
		[Column,        Nullable] public string c_ogrn             { get; set; } // character varying(13)
		[Column,        Nullable] public string c_checking_account { get; set; } // character varying(20)
		[Column,        Nullable] public string c_kor_account      { get; set; } // character varying(20)
		[Column,        Nullable] public int?   imp_id             { get; set; } // integer
		[Column,        Nullable] public string c_code             { get; set; } // character varying(2)
		[Column,     NotNull    ] public int    f_department       { get; set; } // integer

		#region Associations

		/// <summary>
		/// cs_banks_fkey_f_department
		/// </summary>
		[Association(ThisKey="f_department", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_banks_fkey_f_department")]
		public public_cs_departments csbanksfkeyfdepartment { get; set; }

		/// <summary>
		/// cs_banks_fkey_f_type
		/// </summary>
		[Association(ThisKey="f_type", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_banks_fkey_f_type")]
		public public_cs_bank_types csbanksfkeyftype { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cs_boss_posts")]
	public partial class public_cs_boss_posts
	{
		[PrimaryKey, Identity] public int    id     { get; set; } // integer
		[Column,     NotNull ] public string c_name { get; set; } // character varying(128)
	}

	[Table(Schema="public", Name="cs_departments")]
	public partial class public_cs_departments
	{
		[PrimaryKey, Identity   ] public int    id            { get; set; } // integer
		[Column,     NotNull    ] public string c_name        { get; set; } // character varying(128)
		[Column,        Nullable] public string c_boss_fio    { get; set; } // character varying(128)
		[Column,        Nullable] public string c_glavbuh_fio { get; set; } // character varying(128)
		[Column,        Nullable] public string c_alias       { get; set; } // character varying(100)
	}

	[Table(Schema="public", Name="cs_document_issues_orgs")]
	public partial class public_cs_document_issues_orgs
	{
		[PrimaryKey, Identity   ] public int    id      { get; set; } // integer
		[Column,        Nullable] public string c_code  { get; set; } // character varying(10)
		[Column,     NotNull    ] public string c_name  { get; set; } // character varying(256)
		[Column,     NotNull    ] public int    f_group { get; set; } // integer
		[Column,        Nullable] public int?   imp_id  { get; set; } // integer

		#region Associations

		/// <summary>
		/// cs_document_issues_orgs_fkey_f_group
		/// </summary>
		[Association(ThisKey="f_group", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_document_issues_orgs_fkey_f_group")]
		public public_cs_document_type_groups csdocumentissuesorgsfkeyfgroup { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cs_document_type_groups")]
	public partial class public_cs_document_type_groups
	{
		[PrimaryKey, Identity   ] public int    id      { get; set; } // integer
		[Column,     NotNull    ] public string c_name  { get; set; } // character varying(128)
		[Column,        Nullable] public string c_alias { get; set; } // character varying(128)
	}

	[Table(Schema="public", Name="cs_document_types")]
	public partial class public_cs_document_types
	{
		[PrimaryKey, Identity   ] public int    id          { get; set; } // integer
		[Column,     NotNull    ] public string c_name      { get; set; } // character varying(128)
		[Column,     NotNull    ] public int    f_group     { get; set; } // integer
		[Column,        Nullable] public string c_code      { get; set; } // character varying(50)
		[Column,        Nullable] public string c_code_rsmv { get; set; } // character varying(10)
		[Column,        Nullable] public string c_code_ru   { get; set; } // character varying(2000)

		#region Associations

		/// <summary>
		/// cd_document_types_fkey_f_group
		/// </summary>
		[Association(ThisKey="f_group", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cd_document_types_fkey_f_group")]
		public public_cs_document_type_groups cddocumenttypesfkeyfgroup { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cs_house_type")]
	public partial class public_cs_house_type
	{
		[PrimaryKey, Identity] public int    id     { get; set; } // integer
		[Column,     Nullable] public string c_type { get; set; } // character varying(50)
	}

	[Table(Schema="public", Name="cs_martial_status")]
	public partial class public_cs_martial_status
	{
		[PrimaryKey, Identity] public int    id       { get; set; } // integer
		[Column,     Nullable] public string c_status { get; set; } // character varying(50)
	}

	[Table(Schema="public", Name="cs_organizations")]
	public partial class public_cs_organizations
	{
		[PrimaryKey, Identity   ] public int    id                    { get; set; } // integer
		[Column,     NotNull    ] public string c_name                { get; set; } // character varying(250)
		[Column,        Nullable] public string c_name_rp             { get; set; } // character varying(250)
		[Column,        Nullable] public string c_name_short          { get; set; } // character varying(250)
		[Column,        Nullable] public string c_kpos                { get; set; } // character varying(6)
		[Column,        Nullable] public string c_boss_fio            { get; set; } // character varying(250)
		[Column,        Nullable] public int?   n_year                { get; set; } // integer
		[Column,        Nullable] public int?   n_month               { get; set; } // integer
		[Column,        Nullable] public int?   n_num_ved             { get; set; } // integer
		[Column,        Nullable] public int?   n_year_begin          { get; set; } // integer
		[Column,        Nullable] public int?   n_month_begin         { get; set; } // integer
		[Column,     NotNull    ] public int    f_boss_post           { get; set; } // integer
		[Column,     NotNull    ] public int    f_department          { get; set; } // integer
		[Column,        Nullable] public string c_code_egiso          { get; set; } // character varying(20)
		[Column,        Nullable] public string c_code_provider_egiso { get; set; } // character varying(20)
		[Column,        Nullable] public string c_glavbuh_fio         { get; set; } // character varying(250)
		[Column,        Nullable] public string c_registry_number     { get; set; } // character varying(14)
		[Column,        Nullable] public string c_inn                 { get; set; } // character(10)
		[Column,        Nullable] public string c_kpp                 { get; set; } // character(9)
		[Column,        Nullable] public string c_ogrn                { get; set; } // character(13)

		#region Associations

		/// <summary>
		/// cs_organizations_fkey_f_boss_posts
		/// </summary>
		[Association(ThisKey="f_boss_post", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_organizations_fkey_f_boss_posts")]
		public public_cs_boss_posts csorganizationsfkeyfbosspost { get; set; }

		/// <summary>
		/// cs_organizations_fkey_f_department
		/// </summary>
		[Association(ThisKey="f_department", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_organizations_fkey_f_department")]
		public public_cs_departments csorganizationsfkeyfdepartment { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="cs_sex")]
	public partial class public_cs_sex
	{
		[PrimaryKey, Identity] public int    id      { get; set; } // integer
		[Column,     Nullable] public string c_name  { get; set; } // character varying(10)
		[Column,     Nullable] public string c_const { get; set; } // character varying(10)
	}

	[Table(Schema="public", Name="cs_subsystems")]
	public partial class public_cs_subsystems
	{
		[PrimaryKey, Identity   ] public int    id           { get; set; } // integer
		[Column,     NotNull    ] public string c_name       { get; set; } // character varying(128)
		[Column,     NotNull    ] public int    f_department { get; set; } // integer
		[Column,        Nullable] public string c_alias      { get; set; } // character varying(64)

		#region Associations

		/// <summary>
		/// cs_subsystem_fkey_f_department
		/// </summary>
		[Association(ThisKey="f_department", OtherKey="id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="cs_subsystem_fkey_f_department")]
		public public_cs_departments cssubsystemfkeyfdepartment { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="XPObjectType")]
	public partial class public_XPObjectType
	{
		[PrimaryKey, Identity] public int    OID          { get; set; } // integer
		[Column,     Nullable] public string TypeName     { get; set; } // character varying(254)
		[Column,     Nullable] public string AssemblyName { get; set; } // character varying(254)
	}

	[Table(Schema="subsidy", Name="cs_family_relations")]
	public partial class subsidy_cs_family_relations
	{
		[PrimaryKey, Identity   ] public int    id      { get; set; } // integer
		[Column,     NotNull    ] public string c_name  { get; set; } // character varying(64)
		[Column,        Nullable] public string c_alias { get; set; } // character varying(64)
	}

	[Table(Schema="subsidy", Name="cs_payment_methods")]
	public partial class subsidy_cs_payment_methods
	{
		[PrimaryKey, Identity   ] public int    id      { get; set; } // integer
		[Column,     NotNull    ] public string c_name  { get; set; } // character varying(128)
		[Column,        Nullable] public string c_alias { get; set; } // character varying(64)
	}

	public static partial class SqlFunctions
	{
		#region get_max_deal_number

		[Sql.Function(Name=".get_max_deal_number", ServerSideOnly=true)]
		public static int? get_max_deal_number()
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region set_archive_status

		[Sql.Function(Name=".set_archive_status", ServerSideOnly=true)]
		public static object set_archive_status()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}
}
