//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections;
using System.Collections.Generic;
using System.Net.NetworkInformation;

using LinqToDB;
using LinqToDB.Mapping;

using NpgsqlTypes;

namespace SocialTargetHelpAPIServer.Models
{
	/// <summary>
	/// Database       : social_target_help
	/// Data Source    : tcp://192.168.2.179:5432
	/// Server Version : 9.5.13
	/// </summary>
	public partial class STH : LinqToDB.Data.DataConnection
	{
		public ITable<api_req_requests>                                        api_req_requests                                        { get { return this.GetTable<api_req_requests>(); } }
		public ITable<fatalzp_d_FATALZPRequest>                                fatalzp_d_FATALZPRequest                                { get { return this.GetTable<fatalzp_d_FATALZPRequest>(); } }
		public ITable<fatalzp_d_АдрКЛАДРТип>                                   fatalzp_d_АдрКЛАДРТип                                   { get { return this.GetTable<fatalzp_d_АдрКЛАДРТип>(); } }
		public ITable<fatalzp_d_АдрФИАСТип>                                    fatalzp_d_АдрФИАСТип                                    { get { return this.GetTable<fatalzp_d_АдрФИАСТип>(); } }
		public ITable<fatalzp_d_ВидНаимКодТип>                                 fatalzp_d_ВидНаимКодТип                                 { get { return this.GetTable<fatalzp_d_ВидНаимКодТип>(); } }
		public ITable<fatalzp_d_ВидНаимТип>                                    fatalzp_d_ВидНаимТип                                    { get { return this.GetTable<fatalzp_d_ВидНаимТип>(); } }
		public ITable<fatalzp_d_ГражданствоТип>                                fatalzp_d_ГражданствоТип                                { get { return this.GetTable<fatalzp_d_ГражданствоТип>(); } }
		public ITable<fatalzp_d_ДатаДокТип>                                    fatalzp_d_ДатаДокТип                                    { get { return this.GetTable<fatalzp_d_ДатаДокТип>(); } }
		public ITable<fatalzp_d_ЗапАктТип>                                     fatalzp_d_ЗапАктТип                                     { get { return this.GetTable<fatalzp_d_ЗапАктТип>(); } }
		public ITable<fatalzp_d_МестоТип>                                      fatalzp_d_МестоТип                                      { get { return this.GetTable<fatalzp_d_МестоТип>(); } }
		public ITable<fatalzp_d_МЖПослИн>                                      fatalzp_d_МЖПослИн                                      { get { return this.GetTable<fatalzp_d_МЖПослИн>(); } }
		public ITable<fatalzp_d_МЖПослРФ>                                      fatalzp_d_МЖПослРФ                                      { get { return this.GetTable<fatalzp_d_МЖПослРФ>(); } }
		public ITable<fatalzp_d_МЖПослТип>                                     fatalzp_d_МЖПослТип                                     { get { return this.GetTable<fatalzp_d_МЖПослТип>(); } }
		public ITable<fatalzp_d_НомерТип>                                      fatalzp_d_НомерТип                                      { get { return this.GetTable<fatalzp_d_НомерТип>(); } }
		public ITable<fatalzp_d_НомерТипЗданиеCollection_fatalzp_d_А_BF94C0E4> fatalzp_d_НомерТипЗданиеCollection_fatalzp_d_А_BF94C0E4 { get { return this.GetTable<fatalzp_d_НомерТипЗданиеCollection_fatalzp_d_А_BF94C0E4>(); } }
		public ITable<fatalzp_d_ОрганЗАГСТип>                                  fatalzp_d_ОрганЗАГСТип                                  { get { return this.GetTable<fatalzp_d_ОрганЗАГСТип>(); } }
		public ITable<fatalzp_d_ПрдСведРег>                                    fatalzp_d_ПрдСведРег                                    { get { return this.GetTable<fatalzp_d_ПрдСведРег>(); } }
		public ITable<fatalzp_d_СведДокОснТип>                                 fatalzp_d_СведДокОснТип                                 { get { return this.GetTable<fatalzp_d_СведДокОснТип>(); } }
		public ITable<fatalzp_d_СведДокТип>                                    fatalzp_d_СведДокТип                                    { get { return this.GetTable<fatalzp_d_СведДокТип>(); } }
		public ITable<fatalzp_d_СведИзмАГСТип>                                 fatalzp_d_СведИзмАГСТип                                 { get { return this.GetTable<fatalzp_d_СведИзмАГСТип>(); } }
		public ITable<fatalzp_d_СведРегСмерт>                                  fatalzp_d_СведРегСмерт                                  { get { return this.GetTable<fatalzp_d_СведРегСмерт>(); } }
		public ITable<fatalzp_d_СведСвидетТип>                                 fatalzp_d_СведСвидетТип                                 { get { return this.GetTable<fatalzp_d_СведСвидетТип>(); } }
		public ITable<fatalzp_d_СведСвидетТипПовтСвидетCollec_AD026169>        fatalzp_d_СведСвидетТипПовтСвидетCollec_AD026169        { get { return this.GetTable<fatalzp_d_СведСвидетТипПовтСвидетCollec_AD026169>(); } }
		public ITable<fatalzp_d_СведУмер>                                      fatalzp_d_СведУмер                                      { get { return this.GetTable<fatalzp_d_СведУмер>(); } }
		public ITable<fatalzp_d_СтатусЗаписи>                                  fatalzp_d_СтатусЗаписи                                  { get { return this.GetTable<fatalzp_d_СтатусЗаписи>(); } }
		public ITable<fatalzp_d_ТипНаимТип>                                    fatalzp_d_ТипНаимТип                                    { get { return this.GetTable<fatalzp_d_ТипНаимТип>(); } }
		public ITable<fatalzp_d_УдЛичнФЛТип>                                   fatalzp_d_УдЛичнФЛТип                                   { get { return this.GetTable<fatalzp_d_УдЛичнФЛТип>(); } }
		public ITable<fatalzp_d_ФИОПрТип>                                      fatalzp_d_ФИОПрТип                                      { get { return this.GetTable<fatalzp_d_ФИОПрТип>(); } }
		public ITable<fatalzp_sv_cd_umer>                                      fatalzp_sv_cd_umer                                      { get { return this.GetTable<fatalzp_sv_cd_umer>(); } }
		public ITable<fatalzp_sv_cd_umer_all>                                  fatalzp_sv_cd_umer_all                                  { get { return this.GetTable<fatalzp_sv_cd_umer_all>(); } }
		public ITable<fatalzp_sv_cd_umer_cut>                                  fatalzp_sv_cd_umer_cut                                  { get { return this.GetTable<fatalzp_sv_cd_umer_cut>(); } }
		public ITable<fatalzp_sv_cd_umer_general>                              fatalzp_sv_cd_umer_general                              { get { return this.GetTable<fatalzp_sv_cd_umer_general>(); } }
		public ITable<fatalzp_sv_cd_umer_pension>                              fatalzp_sv_cd_umer_pension                              { get { return this.GetTable<fatalzp_sv_cd_umer_pension>(); } }
		public ITable<fatalzp_sv_cd_umer_poor>                                 fatalzp_sv_cd_umer_poor                                 { get { return this.GetTable<fatalzp_sv_cd_umer_poor>(); } }
		public ITable<fatalzp_sv_cd_umer_subsidy>                              fatalzp_sv_cd_umer_subsidy                              { get { return this.GetTable<fatalzp_sv_cd_umer_subsidy>(); } }
		public ITable<sozags_СОЗАГС_1>                                         sozags_СОЗАГС_1                                         { get { return this.GetTable<sozags_СОЗАГС_1>(); } }
		public ITable<sozags_СОЗАГС_1В>                                        sozags_СОЗАГС_1В                                        { get { return this.GetTable<sozags_СОЗАГС_1В>(); } }
		public ITable<zags_ОКСМ>                                               zags_ОКСМ                                               { get { return this.GetTable<zags_ОКСМ>(); } }
		public ITable<zags_СВЗАГС>                                             zags_СВЗАГС                                             { get { return this.GetTable<zags_СВЗАГС>(); } }
		public ITable<zags_СДРАГС>                                             zags_СДРАГС                                             { get { return this.GetTable<zags_СДРАГС>(); } }
		public ITable<zags_СПДУЛ>                                              zags_СПДУЛ                                              { get { return this.GetTable<zags_СПДУЛ>(); } }
		public ITable<zags_СТАГС>                                              zags_СТАГС                                              { get { return this.GetTable<zags_СТАГС>(); } }

		partial void InitMappingSchema()
		{
		}

		public STH()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public STH(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="api_req", Name="requests")]
	public partial class api_req_requests
	{
		[PrimaryKey, Identity] public int       id        { get; set; } // integer
		[Column,     Nullable] public DateTime? req_date  { get; set; } // timestamp (6) without time zone
		[Column,     Nullable] public string    request   { get; set; } // character varying
		[Column,     Nullable] public string    response  { get; set; } // character varying
		[Column,     Nullable] public string    from_whom { get; set; } // character varying(256)
	}

	[Table(Schema="fatalzp", Name="d_FATALZPRequest")]
	public partial class fatalzp_d_FATALZPRequest
	{
		[PrimaryKey, NotNull    ] public Guid      Id          { get; set; } // uuid
		[Column,        Nullable] public string    ИдСвед      { get; set; } // character varying(36)
		[Column,        Nullable] public DateTime? ДатаСвед    { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public DateTime? CreateDate  { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public int?      Version     { get; set; } // integer
		[Column,        Nullable] public DateTime? ConvertDate { get; set; } // timestamp (6) without time zone
	}

	[Table(Schema="fatalzp", Name="d_АдрКЛАДРТип")]
	public partial class fatalzp_d_АдрКЛАДРТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id         { get; set; } // uuid
		[Column,        Nullable] public string Индекс     { get; set; } // character varying(6)
		[Column,        Nullable] public string КодРегион  { get; set; } // character varying(2)
		[Column,        Nullable] public string НаимРегион { get; set; } // character varying(50)
		[Column,        Nullable] public string Район      { get; set; } // character varying(50)
		[Column,        Nullable] public string Город      { get; set; } // character varying(50)
		[Column,        Nullable] public string НаселПункт { get; set; } // character varying(50)
		[Column,        Nullable] public string Улица      { get; set; } // character varying(50)
		[Column,        Nullable] public string Дом        { get; set; } // character varying(20)
		[Column,        Nullable] public string Корпус     { get; set; } // character varying(20)
		[Column,        Nullable] public string Кварт      { get; set; } // character varying(20)
	}

	[Table(Schema="fatalzp", Name="d_АдрФИАСТип")]
	public partial class fatalzp_d_АдрФИАСТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id              { get; set; } // uuid
		[Column,        Nullable] public string Регион          { get; set; } // character varying(2)
		[Column,        Nullable] public string НаимРегион      { get; set; } // character varying(50)
		[Column,        Nullable] public Guid?  МуниципРайон    { get; set; } // uuid
		[Column,        Nullable] public Guid?  ГородСелПоселен { get; set; } // uuid
		[Column,        Nullable] public Guid?  НаселенПункт    { get; set; } // uuid
		[Column,        Nullable] public Guid?  ЭлПланСтруктур  { get; set; } // uuid
		[Column,        Nullable] public Guid?  ЭлУлДорСети     { get; set; } // uuid
		[Column,        Nullable] public string ЗемелУчасток    { get; set; } // character varying(50)
		[Column,        Nullable] public Guid?  ПомещЗдания     { get; set; } // uuid
		[Column,        Nullable] public Guid?  ПомещКвартиры   { get; set; } // uuid
		[Column,        Nullable] public string ИдНом           { get; set; } // character varying(36)
		[Column,        Nullable] public Guid?  FiasId          { get; set; } // uuid
		[Column,        Nullable] public string Индекс          { get; set; } // character varying(6)

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_АдрФИАСТип_ГородСелПо_060CB91A
		/// </summary>
		[Association(ThisKey="ГородСелПоселен", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_АдрФИАСТип_ГородСелПо_060CB91A")]
		public fatalzp_d_ВидНаимКодТип dАдрФИАСТипГородСелПо060CB91A { get; set; }

		/// <summary>
		/// FK_fatalzp_d_АдрФИАСТип_МуниципРай_30395C9F
		/// </summary>
		[Association(ThisKey="МуниципРайон", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_АдрФИАСТип_МуниципРай_30395C9F")]
		public fatalzp_d_ВидНаимКодТип dАдрФИАСТипМуниципРай30395C9F { get; set; }

		/// <summary>
		/// FK_fatalzp_d_АдрФИАСТип_НаселенПун_C3A2560D
		/// </summary>
		[Association(ThisKey="НаселенПункт", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_АдрФИАСТип_НаселенПун_C3A2560D")]
		public fatalzp_d_ВидНаимТип dАдрФИАСТипНаселенПунC3A2560D { get; set; }

		/// <summary>
		/// FK_fatalzp_d_АдрФИАСТип_ПомещЗдани_77790FC6
		/// </summary>
		[Association(ThisKey="ПомещЗдания", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_АдрФИАСТип_ПомещЗдани_77790FC6")]
		public fatalzp_d_НомерТип dАдрФИАСТипПомещЗдани77790FC { get; set; }

		/// <summary>
		/// FK_fatalzp_d_АдрФИАСТип_ПомещКварт_9CB46192
		/// </summary>
		[Association(ThisKey="ПомещКвартиры", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_АдрФИАСТип_ПомещКварт_9CB46192")]
		public fatalzp_d_НомерТип dАдрФИАСТипПомещКварт9CB { get; set; }

		/// <summary>
		/// FK_fatalzp_d_АдрФИАСТип_ЭлПланСтру_7D03E2B3
		/// </summary>
		[Association(ThisKey="ЭлПланСтруктур", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_АдрФИАСТип_ЭлПланСтру_7D03E2B3")]
		public fatalzp_d_ТипНаимТип dАдрФИАСТипЭлПланСтру7D03E2B { get; set; }

		/// <summary>
		/// FK_fatalzp_d_АдрФИАСТип_ЭлУлДорСет_AA464B7C
		/// </summary>
		[Association(ThisKey="ЭлУлДорСети", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_АдрФИАСТип_ЭлУлДорСет_AA464B7C")]
		public fatalzp_d_ТипНаимТип dАдрФИАСТипЭлУлДорСетAA464B7C { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_ВидНаимКодТип")]
	public partial class fatalzp_d_ВидНаимКодТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id     { get; set; } // uuid
		[Column,        Nullable] public char?  ВидКод { get; set; } // character varying(1)
		[Column,        Nullable] public string Наим   { get; set; } // character varying(255)
	}

	[Table(Schema="fatalzp", Name="d_ВидНаимТип")]
	public partial class fatalzp_d_ВидНаимТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id   { get; set; } // uuid
		[Column,        Nullable] public string Вид  { get; set; } // character varying(50)
		[Column,        Nullable] public string Наим { get; set; } // character varying(255)
	}

	[Table(Schema="fatalzp", Name="d_ГражданствоТип")]
	public partial class fatalzp_d_ГражданствоТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id         { get; set; } // uuid
		[Column,        Nullable] public string ОКСМ       { get; set; } // character varying(3)
		[Column,        Nullable] public string НаимСтраны { get; set; } // character varying(255)
		[Column,        Nullable] public Guid?  Страна     { get; set; } // uuid

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_ГражданствоТип_Страна_DCF59FEB
		/// </summary>
		[Association(ThisKey="Страна", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_ГражданствоТип_Страна_DCF59FEB")]
		public zags_ОКСМ dГражданствоТипСтранаDCF59FEB { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_ДатаДокТип")]
	public partial class fatalzp_d_ДатаДокТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id      { get; set; } // uuid
		[Column,        Nullable] public string День    { get; set; } // character varying(2)
		[Column,        Nullable] public int?   ПрДень  { get; set; } // integer
		[Column,        Nullable] public string Месяц   { get; set; } // character varying(2)
		[Column,        Nullable] public int?   ПрМесяц { get; set; } // integer
		[Column,        Nullable] public string Год     { get; set; } // character varying(10)
	}

	[Table(Schema="fatalzp", Name="d_ЗапАктТип")]
	public partial class fatalzp_d_ЗапАктТип
	{
		[PrimaryKey, NotNull    ] public Guid      Id           { get; set; } // uuid
		[Column,        Nullable] public Guid?     ОрганЗАГС    { get; set; } // uuid
		[Column,        Nullable] public Guid?     ЗАГС         { get; set; } // uuid
		[Column,        Nullable] public string    ТипАГС       { get; set; } // character varying(2)
		[Column,        Nullable] public Guid?     ТипАкт       { get; set; } // uuid
		[Column,        Nullable] public string    НаимТипЗапис { get; set; } // character varying(100)
		[Column,        Nullable] public string    НомерЗапис   { get; set; } // character varying(22)
		[Column,        Nullable] public DateTime? ДатаЗапис    { get; set; } // timestamp (6) without time zone

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_ЗапАктТип_ЗАГС_EC19214A
		/// </summary>
		[Association(ThisKey="ЗАГС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_ЗапАктТип_ЗАГС_EC19214A")]
		public sozags_СОЗАГС_1 dЗапАктТипЗАГСEC19214A { get; set; }

		/// <summary>
		/// FK_fatalzp_d_ЗапАктТип_ОрганЗАГС_3A8F873D
		/// </summary>
		[Association(ThisKey="ОрганЗАГС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_ЗапАктТип_ОрганЗАГС_3A8F873D")]
		public fatalzp_d_ОрганЗАГСТип dЗапАктТипОрганЗАГС3A8F873D { get; set; }

		/// <summary>
		/// FK_fatalzp_d_ЗапАктТип_ТипАкт_CDDCE3EE
		/// </summary>
		[Association(ThisKey="ТипАкт", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_ЗапАктТип_ТипАкт_CDDCE3EE")]
		public zags_СТАГС dЗапАктТипТипАктCDDCE3EE { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_МестоТип")]
	public partial class fatalzp_d_МестоТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id          { get; set; } // uuid
		[Column,        Nullable] public int?   ПризнМесто  { get; set; } // integer
		[Column,        Nullable] public string МестоТекст  { get; set; } // character varying(512)
		[Column,        Nullable] public string КодСтраны   { get; set; } // character varying(3)
		[Column,        Nullable] public Guid?  Страна      { get; set; } // uuid
		[Column,        Nullable] public string НаимСтраны  { get; set; } // character varying(255)
		[Column,        Nullable] public string Регион      { get; set; } // character varying(2)
		[Column,        Nullable] public string НаимСубъект { get; set; } // character varying(50)
		[Column,        Nullable] public string Район       { get; set; } // character varying(50)
		[Column,        Nullable] public string Город       { get; set; } // character varying(50)
		[Column,        Nullable] public string НаселПункт  { get; set; } // character varying(50)
		[Column,        Nullable] public string ОКТМО       { get; set; } // character varying(11)
		[Column,        Nullable] public string OktmoShort  { get; set; } // character varying(5)

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_МестоТип_Страна_636D8DAF
		/// </summary>
		[Association(ThisKey="Страна", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_МестоТип_Страна_636D8DAF")]
		public zags_ОКСМ dМестоТипСтрана636D8DAF { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_МЖПослИн")]
	public partial class fatalzp_d_МЖПослИн
	{
		[PrimaryKey, NotNull    ] public Guid   Id         { get; set; } // uuid
		[Column,        Nullable] public string ОКСМ       { get; set; } // character varying(3)
		[Column,        Nullable] public Guid?  Страна     { get; set; } // uuid
		[Column,        Nullable] public string НаимСтраны { get; set; } // character varying(255)
		[Column,        Nullable] public string АдрТекст   { get; set; } // character varying(512)

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_МЖПослИн_Страна_DE861262
		/// </summary>
		[Association(ThisKey="Страна", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_МЖПослИн_Страна_DE861262")]
		public zags_ОКСМ dМЖПослИнСтранаDE { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_МЖПослРФ")]
	public partial class fatalzp_d_МЖПослРФ
	{
		[PrimaryKey, NotNull    ] public Guid   Id         { get; set; } // uuid
		[Column,        Nullable] public Guid?  АдрКЛАДР   { get; set; } // uuid
		[Column,        Nullable] public Guid?  АдрФИАС    { get; set; } // uuid
		[Column,        Nullable] public string АдрРФТекст { get; set; } // character varying(512)
		[Column,        Nullable] public int?   ПрТипАдрРФ { get; set; } // integer
		[Column,        Nullable] public string ОКТМО      { get; set; } // character varying(11)
		[Column,        Nullable] public string OktmoShort { get; set; } // character varying(5)

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_МЖПослРФ_АдрКЛАДР_A0316F8F
		/// </summary>
		[Association(ThisKey="АдрКЛАДР", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_МЖПослРФ_АдрКЛАДР_A0316F8F")]
		public fatalzp_d_АдрКЛАДРТип dМЖПослРФАдрКЛАДРA0316F8F { get; set; }

		/// <summary>
		/// FK_fatalzp_d_МЖПослРФ_АдрФИАС_5880A2E2
		/// </summary>
		[Association(ThisKey="АдрФИАС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_МЖПослРФ_АдрФИАС_5880A2E2")]
		public fatalzp_d_АдрФИАСТип dМЖПослРФАдрФИАС5880A2E { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_МЖПослТип")]
	public partial class fatalzp_d_МЖПослТип
	{
		[PrimaryKey, NotNull    ] public Guid  Id       { get; set; } // uuid
		[Column,        Nullable] public Guid? МЖПослИн { get; set; } // uuid
		[Column,        Nullable] public Guid? МЖПослРФ { get; set; } // uuid

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_МЖПослТип_МЖПослИн_0DCD02F3
		/// </summary>
		[Association(ThisKey="МЖПослИн", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_МЖПослТип_МЖПослИн_0DCD02F3")]
		public fatalzp_d_МЖПослИн dМЖПослТипМЖПослИн0DCD02F { get; set; }

		/// <summary>
		/// FK_fatalzp_d_МЖПослТип_МЖПослРФ_0DCD1EEA
		/// </summary>
		[Association(ThisKey="МЖПослРФ", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_МЖПослТип_МЖПослРФ_0DCD1EEA")]
		public fatalzp_d_МЖПослРФ dМЖПослТипМЖПослРФ0DCD1EEA { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_НомерТип")]
	public partial class fatalzp_d_НомерТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id    { get; set; } // uuid
		[Column,        Nullable] public string Тип   { get; set; } // character varying(50)
		[Column,        Nullable] public string Номер { get; set; } // character varying(255)
	}

	[Table(Schema="fatalzp", Name="d_НомерТипЗданиеCollection_fatalzp_d_А_BF94C0E4")]
	public partial class fatalzp_d_НомерТипЗданиеCollection_fatalzp_d_А_BF94C0E4
	{
		[Column,        Nullable] public Guid? АдрФИАСТипCollection { get; set; } // uuid
		[Column,        Nullable] public Guid? ЗданиеCollection     { get; set; } // uuid
		[PrimaryKey, NotNull    ] public Guid  OID                  { get; set; } // uuid
		[Column,        Nullable] public int?  OptimisticLockField  { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_НомерТипЗданиеCollection_fa_52FFE115
		/// </summary>
		[Association(ThisKey="ЗданиеCollection", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_НомерТипЗданиеCollection_fa_52FFE115")]
		public fatalzp_d_НомерТип dНомерТипЗданиеCollectionfa52FFE { get; set; }

		/// <summary>
		/// FK_fatalzp_d_НомерТипЗданиеCollection_fa_EBC7492B
		/// </summary>
		[Association(ThisKey="АдрФИАСТипCollection", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_НомерТипЗданиеCollection_fa_EBC7492B")]
		public fatalzp_d_АдрФИАСТип dНомерТипЗданиеCollectionfaEBC7492B { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_ОрганЗАГСТип")]
	public partial class fatalzp_d_ОрганЗАГСТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id       { get; set; } // uuid
		[Column,        Nullable] public string НаимЗАГС { get; set; } // character varying(1000)
		[Column,        Nullable] public string КодЗАГС  { get; set; } // character varying(8)
	}

	[Table(Schema="fatalzp", Name="d_ПрдСведРег")]
	public partial class fatalzp_d_ПрдСведРег
	{
		[PrimaryKey, NotNull    ] public Guid  Id       { get; set; } // uuid
		[Column,        Nullable] public Guid? СведУмер { get; set; } // uuid

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_ПрдСведРег_СведУмер_6CAEF2E7
		/// </summary>
		[Association(ThisKey="СведУмер", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_ПрдСведРег_СведУмер_6CAEF2E7")]
		public fatalzp_d_СведУмер dПрдСведРегСведУмер6CAEF2E { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_СведДокОснТип")]
	public partial class fatalzp_d_СведДокОснТип
	{
		[PrimaryKey, NotNull    ] public Guid  Id        { get; set; } // uuid
		[Column,        Nullable] public Guid? ДокОсн    { get; set; } // uuid
		[Column,        Nullable] public Guid? ЗапАктОсн { get; set; } // uuid

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_СведДокОснТип_ДокОсн_EDC3D444
		/// </summary>
		[Association(ThisKey="ДокОсн", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведДокОснТип_ДокОсн_EDC3D444")]
		public fatalzp_d_СведДокТип dСведДокОснТипДокОснEDC3D { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведДокОснТип_ЗапАктО_356408B0
		/// </summary>
		[Association(ThisKey="ЗапАктОсн", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведДокОснТип_ЗапАктО_356408B0")]
		public fatalzp_d_ЗапАктТип dСведДокОснТипЗапАктО356408B { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_СведДокТип")]
	public partial class fatalzp_d_СведДокТип
	{
		[PrimaryKey, NotNull    ] public Guid      Id               { get; set; } // uuid
		[Column,        Nullable] public string    НаимОрг          { get; set; } // character varying(255)
		[Column,        Nullable] public Guid?     ФИОИП            { get; set; } // uuid
		[Column,        Nullable] public Guid?     ФИОФЛ            { get; set; } // uuid
		[Column,        Nullable] public string    КодДок           { get; set; } // character varying(5)
		[Column,        Nullable] public Guid?     ВидДок           { get; set; } // uuid
		[Column,        Nullable] public string    НаимДок          { get; set; } // character varying(500)
		[Column,        Nullable] public string    СерНомДок        { get; set; } // character varying(25)
		[Column,        Nullable] public DateTime? ДатаДок          { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public bool?     ДатаДокSpecified { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_СведДокТип_ВидДок_B7F23A28
		/// </summary>
		[Association(ThisKey="ВидДок", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведДокТип_ВидДок_B7F23A28")]
		public zags_СДРАГС dСведДокТипВидДокB7F23A { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведДокТип_ФИОИП_4165625E
		/// </summary>
		[Association(ThisKey="ФИОИП", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведДокТип_ФИОИП_4165625E")]
		public fatalzp_d_ФИОПрТип dСведДокТипФИОИП4165625E { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведДокТип_ФИОФЛ_41657C5A
		/// </summary>
		[Association(ThisKey="ФИОФЛ", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведДокТип_ФИОФЛ_41657C5A")]
		public fatalzp_d_ФИОПрТип dСведДокТипФИОФЛ41657C5A { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_СведИзмАГСТип")]
	public partial class fatalzp_d_СведИзмАГСТип
	{
		[PrimaryKey, NotNull    ] public Guid      Id               { get; set; } // uuid
		[Column,        Nullable] public int?      ПрСведДокИспрАГС { get; set; } // integer
		[Column,        Nullable] public Guid?     СведДокИспрАГС   { get; set; } // uuid
		[Column,        Nullable] public string    КодВидСвед       { get; set; } // character varying(4)
		[Column,        Nullable] public string    НаимВидСвед      { get; set; } // character varying(500)
		[Column,        Nullable] public Guid?     ВидСвед          { get; set; } // uuid
		[Column,        Nullable] public DateTime? ДатаВнесИспр     { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    СодержИспр       { get; set; } // character varying(1000)
		[Column,        Nullable] public Guid?     СведРегСмерт     { get; set; } // uuid

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_СведИзмАГСТип_ВидСвед_7339686A
		/// </summary>
		[Association(ThisKey="ВидСвед", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведИзмАГСТип_ВидСвед_7339686A")]
		public zags_СВЗАГС dСведИзмАГСТипВидСвед7339686A { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведИзмАГСТип_СведДок_3A7E8CCA
		/// </summary>
		[Association(ThisKey="СведДокИспрАГС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведИзмАГСТип_СведДок_3A7E8CCA")]
		public fatalzp_d_СведДокОснТип dСведИзмАГСТипСведДок3A7E8CCA { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведИзмАГСТип_СведРег_9A6645EB
		/// </summary>
		[Association(ThisKey="СведРегСмерт", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведИзмАГСТип_СведРег_9A6645EB")]
		public fatalzp_d_СведРегСмерт dСведИзмАГСТипСведРег9A6645EB { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_СведРегСмерт")]
	public partial class fatalzp_d_СведРегСмерт
	{
		[PrimaryKey, NotNull    ] public Guid      Id             { get; set; } // uuid
		[Column,        Nullable] public Guid?     ОрганЗАГС      { get; set; } // uuid
		[Column,        Nullable] public Guid?     ЗАГС           { get; set; } // uuid
		[Column,        Nullable] public Guid?     СтатусЗаписи   { get; set; } // uuid
		[Column,        Nullable] public Guid?     СведСвидет     { get; set; } // uuid
		[Column,        Nullable] public Guid?     ПрдСведРег     { get; set; } // uuid
		[Column,        Nullable] public Guid?     СведВосстанАГС { get; set; } // uuid
		[Column,        Nullable] public Guid?     СведАннулирАГС { get; set; } // uuid
		[Column,        Nullable] public string    НомерЗапис     { get; set; } // character varying(22)
		[Column,        Nullable] public DateTime? ДатаЗапис      { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    НомерВерс      { get; set; } // character varying(3)
		[Column,        Nullable] public DateTime? ДатаВерс       { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public Guid?     FATALZPRequest { get; set; } // uuid

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_FATALZPRequest_BC0DC7CE
		/// </summary>
		[Association(ThisKey="FATALZPRequest", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_FATALZPRequest_BC0DC7CE")]
		public fatalzp_d_FATALZPRequest dСведРегСмертFATALZPRequestBC0DC7CE { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_ЗАГС_44D63034
		/// </summary>
		[Association(ThisKey="ЗАГС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_ЗАГС_44D63034")]
		public sozags_СОЗАГС_1 dСведРегСмертЗАГС44D { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_ОрганЗАГ_7CF70CC8
		/// </summary>
		[Association(ThisKey="ОрганЗАГС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_ОрганЗАГ_7CF70CC8")]
		public fatalzp_d_ОрганЗАГСТип dСведРегСмертОрганЗАГ7CF70CC { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_ПрдСведР_DF04EE77
		/// </summary>
		[Association(ThisKey="ПрдСведРег", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_ПрдСведР_DF04EE77")]
		public fatalzp_d_ПрдСведРег dСведРегСмертПрдСведРDF04EE { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_СведАнну_BBC5EA66
		/// </summary>
		[Association(ThisKey="СведАннулирАГС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_СведАнну_BBC5EA66")]
		public fatalzp_d_СведИзмАГСТип dСведРегСмертСведАннуBBC5EA { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_СведВосс_379DE1AF
		/// </summary>
		[Association(ThisKey="СведВосстанАГС", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_СведВосс_379DE1AF")]
		public fatalzp_d_СведИзмАГСТип dСведРегСмертСведВосс379DE1AF { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_СведСвид_DC83BA81
		/// </summary>
		[Association(ThisKey="СведСвидет", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_СведСвид_DC83BA81")]
		public fatalzp_d_СведСвидетТип dСведРегСмертСведСвидDC83BA { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведРегСмерт_СтатусЗа_593902E2
		/// </summary>
		[Association(ThisKey="СтатусЗаписи", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведРегСмерт_СтатусЗа_593902E2")]
		public fatalzp_d_СтатусЗаписи dСведРегСмертСтатусЗа593902E { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_СведСвидетТип")]
	public partial class fatalzp_d_СведСвидетТип
	{
		[PrimaryKey, NotNull    ] public Guid      Id            { get; set; } // uuid
		[Column,        Nullable] public string    СерияСвидет   { get; set; } // character varying(8)
		[Column,        Nullable] public string    НомерСвидет   { get; set; } // character varying(8)
		[Column,        Nullable] public DateTime? ДатаВыдСвидет { get; set; } // timestamp (6) without time zone
	}

	[Table(Schema="fatalzp", Name="d_СведСвидетТипПовтСвидетCollec_AD026169")]
	public partial class fatalzp_d_СведСвидетТипПовтСвидетCollec_AD026169
	{
		[Column,        Nullable] public Guid? СведРегСмертCollection { get; set; } // uuid
		[Column,        Nullable] public Guid? ПовтСвидетCollection   { get; set; } // uuid
		[PrimaryKey, NotNull    ] public Guid  OID                    { get; set; } // uuid
		[Column,        Nullable] public int?  OptimisticLockField    { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_СведСвидетТипПовтСви_3DB3431F
		/// </summary>
		[Association(ThisKey="СведРегСмертCollection", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведСвидетТипПовтСви_3DB3431F")]
		public fatalzp_d_СведРегСмерт dСведСвидетТипПовтСви3DB3431F { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведСвидетТипПовтСви_D61F4D18
		/// </summary>
		[Association(ThisKey="ПовтСвидетCollection", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведСвидетТипПовтСви_D61F4D18")]
		public fatalzp_d_СведСвидетТип dСведСвидетТипПовтСвиD61F4D { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_СведУмер")]
	public partial class fatalzp_d_СведУмер
	{
		[PrimaryKey, NotNull    ] public Guid      Id                     { get; set; } // uuid
		[Column,        Nullable] public Guid?     Гражданство            { get; set; } // uuid
		[Column,        Nullable] public int?      ПрГражданство          { get; set; } // integer
		[Column,        Nullable] public string    Фамилия                { get; set; } // character varying(60)
		[Column,        Nullable] public string    Имя                    { get; set; } // character varying(60)
		[Column,        Nullable] public string    Отчество               { get; set; } // character varying(60)
		[Column,        Nullable] public Guid?     ДатаРождДок            { get; set; } // uuid
		[Column,        Nullable] public DateTime? ДатаРождКаленд         { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public int?      ПрДатаРожд             { get; set; } // integer
		[Column,        Nullable] public DateTime? BirthDate              { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    BirthDateStr           { get; set; } // character varying(13)
		[Column,        Nullable] public Guid?     МестоРожден            { get; set; } // uuid
		[Column,        Nullable] public int?      ПрМестоРожден          { get; set; } // integer
		[Column,        Nullable] public Guid?     МЖПосл                 { get; set; } // uuid
		[Column,        Nullable] public int?      ПрМЖПосл               { get; set; } // integer
		[Column,        Nullable] public int?      ПрУдЛичнФЛ             { get; set; } // integer
		[Column,        Nullable] public Guid?     УдЛичнФЛ               { get; set; } // uuid
		[Column,        Nullable] public Guid?     ДатаСмертДок           { get; set; } // uuid
		[Column,        Nullable] public DateTime? ДатаСмертКаленд        { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public int?      ПрДатаСмерт            { get; set; } // integer
		[Column,        Nullable] public DateTime? DeathDate              { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    DeathDateStr           { get; set; } // character varying(13)
		[Column,        Nullable] public DateTime? ВремяСмерт             { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public int?      ПрВремяСмерт           { get; set; } // integer
		[Column,        Nullable] public Guid?     МестоСмерт             { get; set; } // uuid
		[Column,        Nullable] public int?      ПрМестоСмерт           { get; set; } // integer
		[Column,        Nullable] public int?      ПрНеустанЛицо          { get; set; } // integer
		[Column,        Nullable] public bool?     ПрНеустанЛицоSpecified { get; set; } // boolean
		[Column,        Nullable] public int?      Пол                    { get; set; } // integer
		[Column,        Nullable] public bool?     ПолSpecified           { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_СведУмер_Гражданство_A7D4E55E
		/// </summary>
		[Association(ThisKey="Гражданство", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведУмер_Гражданство_A7D4E55E")]
		public fatalzp_d_ГражданствоТип dСведУмерГражданствоA7D4E55E { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведУмер_ДатаРождДок_6B6D32D2
		/// </summary>
		[Association(ThisKey="ДатаРождДок", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведУмер_ДатаРождДок_6B6D32D2")]
		public fatalzp_d_ДатаДокТип dСведУмерДатаРождДок6B6D32D { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведУмер_ДатаСмертДок_FC51E710
		/// </summary>
		[Association(ThisKey="ДатаСмертДок", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведУмер_ДатаСмертДок_FC51E710")]
		public fatalzp_d_ДатаДокТип dСведУмерДатаСмертДокFC51E { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведУмер_МестоРожден_68C14DA7
		/// </summary>
		[Association(ThisKey="МестоРожден", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведУмер_МестоРожден_68C14DA7")]
		public fatalzp_d_МестоТип dСведУмерМестоРожден68C14DA { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведУмер_МестоСмерт_249178E4
		/// </summary>
		[Association(ThisKey="МестоСмерт", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведУмер_МестоСмерт_249178E4")]
		public fatalzp_d_МестоТип dСведУмерМестоСмерт249178E { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведУмер_МЖПосл_1A3EF5F2
		/// </summary>
		[Association(ThisKey="МЖПосл", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведУмер_МЖПосл_1A3EF5F2")]
		public fatalzp_d_МЖПослТип dСведУмерМЖПосл1A3EF5F { get; set; }

		/// <summary>
		/// FK_fatalzp_d_СведУмер_УдЛичнФЛ_DDC198B4
		/// </summary>
		[Association(ThisKey="УдЛичнФЛ", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_СведУмер_УдЛичнФЛ_DDC198B4")]
		public fatalzp_d_УдЛичнФЛТип dСведУмерУдЛичнФЛDDC198B { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_СтатусЗаписи")]
	public partial class fatalzp_d_СтатусЗаписи
	{
		[PrimaryKey, NotNull    ] public Guid      Id            { get; set; } // uuid
		[Column,        Nullable] public DateTime? ДатаНачСтатус { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public int?      КодСтатус     { get; set; } // integer
		[Column,        Nullable] public string    НаимСтатус    { get; set; } // character varying(255)
	}

	[Table(Schema="fatalzp", Name="d_ТипНаимТип")]
	public partial class fatalzp_d_ТипНаимТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id   { get; set; } // uuid
		[Column,        Nullable] public string Тип  { get; set; } // character varying(50)
		[Column,        Nullable] public string Наим { get; set; } // character varying(255)
	}

	[Table(Schema="fatalzp", Name="d_УдЛичнФЛТип")]
	public partial class fatalzp_d_УдЛичнФЛТип
	{
		[PrimaryKey, NotNull    ] public Guid      Id               { get; set; } // uuid
		[Column,        Nullable] public string    КодВидДок        { get; set; } // character varying(2)
		[Column,        Nullable] public Guid?     ВидДок           { get; set; } // uuid
		[Column,        Nullable] public string    НаимДок          { get; set; } // character varying(120)
		[Column,        Nullable] public string    СерНомДок        { get; set; } // character varying(25)
		[Column,        Nullable] public DateTime? ДатаДок          { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public bool?     ДатаДокSpecified { get; set; } // boolean
		[Column,        Nullable] public string    ВыдДок           { get; set; } // character varying(255)

		#region Associations

		/// <summary>
		/// FK_fatalzp_d_УдЛичнФЛТип_ВидДок_ABF3354E
		/// </summary>
		[Association(ThisKey="ВидДок", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_fatalzp_d_УдЛичнФЛТип_ВидДок_ABF3354E")]
		public zags_СПДУЛ dУдЛичнФЛТипВидДокABF3354E { get; set; }

		#endregion
	}

	[Table(Schema="fatalzp", Name="d_ФИОПрТип")]
	public partial class fatalzp_d_ФИОПрТип
	{
		[PrimaryKey, NotNull    ] public Guid   Id         { get; set; } // uuid
		[Column,        Nullable] public string Фамилия    { get; set; } // character varying(60)
		[Column,        Nullable] public string Имя        { get; set; } // character varying(60)
		[Column,        Nullable] public string Отчество   { get; set; } // character varying(60)
		[Column,        Nullable] public int?   ПрФамилия  { get; set; } // integer
		[Column,        Nullable] public int?   ПрИмя      { get; set; } // integer
		[Column,        Nullable] public int?   ПрОтчество { get; set; } // integer
	}

	[Table(Schema="fatalzp", Name="sv_cd_umer", IsView=true)]
	public partial class fatalzp_sv_cd_umer
	{
		[Column(SkipOnUpdate=true), Nullable] public long?     row_number      { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public long?     rn              { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public Guid?     svedumer        { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    Фамилия         { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public string    Имя             { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public string    Отчество        { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? BirthDate       { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    BirthDateStr    { get; set; } // character varying(13)
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МестоРожден     { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public int?      Пол             { get; set; } // integer
		[Column(SkipOnUpdate=true), Nullable] public Guid?     Гражданство     { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МЖПосл          { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public DateTime? DeathDate       { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    DeathDateStr    { get; set; } // character varying(13)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ВремяСмерт      { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МестоСмерт      { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public Guid?     sved            { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    НомерЗапис      { get; set; } // character varying(22)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаЗапис       { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    КодЗАГС         { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string    НаимЗАГС        { get; set; } // character varying(1000)
		[Column(SkipOnUpdate=true), Nullable] public string    НаимСтатус      { get; set; } // character varying(255)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаНачСтатус   { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    НаимДок         { get; set; } // character varying(120)
		[Column(SkipOnUpdate=true), Nullable] public string    СерНомДок       { get; set; } // character varying(25)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаДок         { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    ВыдДок          { get; set; } // character varying(255)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаВыдСвидет   { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    СерияСвидет     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string    НомерСвидет     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public Guid?     fatalzprequest  { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    birthoktmoshort { get; set; } // character varying(5)
		[Column(SkipOnUpdate=true), Nullable] public string    deathoktmoshort { get; set; } // character varying(5)
		[Column(SkipOnUpdate=true), Nullable] public string    liveoktmoshort  { get; set; } // character varying(5)
	}

	[Table(Schema="fatalzp", Name="sv_cd_umer_all", IsView=true)]
	public partial class fatalzp_sv_cd_umer_all
	{
		[Column(SkipOnUpdate=true), Nullable] public long?     row_number     { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public Guid?     svedumer       { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    Фамилия        { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public string    Имя            { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public string    Отчество       { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? BirthDate      { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    BirthDateStr   { get; set; } // character varying(13)
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МестоРожден    { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public int?      Пол            { get; set; } // integer
		[Column(SkipOnUpdate=true), Nullable] public Guid?     Гражданство    { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МЖПосл         { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public DateTime? DeathDate      { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    DeathDateStr   { get; set; } // character varying(13)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ВремяСмерт     { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МестоСмерт     { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public Guid?     sved           { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    НомерЗапис     { get; set; } // character varying(22)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаЗапис      { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    КодЗАГС        { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string    НаимЗАГС       { get; set; } // character varying(1000)
		[Column(SkipOnUpdate=true), Nullable] public string    НаимСтатус     { get; set; } // character varying(255)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаНачСтатус  { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    НаимДок        { get; set; } // character varying(120)
		[Column(SkipOnUpdate=true), Nullable] public string    СерНомДок      { get; set; } // character varying(25)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаДок        { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    ВыдДок         { get; set; } // character varying(255)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаВыдСвидет  { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    СерияСвидет    { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string    НомерСвидет    { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public Guid?     fatalzprequest { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public DateTime? CreateDate     { get; set; } // timestamp (6) without time zone
	}

	[Table(Schema="fatalzp", Name="sv_cd_umer_cut", IsView=true)]
	public partial class fatalzp_sv_cd_umer_cut
	{
		[Column(SkipOnUpdate=true), Nullable] public long?     row_number     { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public long?     rn             { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public Guid?     svedumer       { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    Фамилия        { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public string    Имя            { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public string    Отчество       { get; set; } // character varying(60)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? BirthDate      { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    BirthDateStr   { get; set; } // character varying(13)
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МестоРожден    { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public int?      Пол            { get; set; } // integer
		[Column(SkipOnUpdate=true), Nullable] public Guid?     Гражданство    { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МЖПосл         { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    АдрРФТекст     { get; set; } // character varying(512)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? DeathDate      { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    DeathDateStr   { get; set; } // character varying(13)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ВремяСмерт     { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public Guid?     МестоСмерт     { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public Guid?     sved           { get; set; } // uuid
		[Column(SkipOnUpdate=true), Nullable] public string    НомерЗапис     { get; set; } // character varying(22)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаЗапис      { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    КодЗАГС        { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string    НаимЗАГС       { get; set; } // character varying(1000)
		[Column(SkipOnUpdate=true), Nullable] public string    НаимСтатус     { get; set; } // character varying(255)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаНачСтатус  { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    НаимДок        { get; set; } // character varying(120)
		[Column(SkipOnUpdate=true), Nullable] public string    СерНомДок      { get; set; } // character varying(25)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаДок        { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    ВыдДок         { get; set; } // character varying(255)
		[Column(SkipOnUpdate=true), Nullable] public DateTime? ДатаВыдСвидет  { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string    СерияСвидет    { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string    НомерСвидет    { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public Guid?     fatalzprequest { get; set; } // uuid
	}

	[Table(Schema="fatalzp", Name="sv_cd_umer_general", IsView=true)]
	public partial class fatalzp_sv_cd_umer_general
	{
		[Column(SkipOnUpdate=true), Nullable] public long?       row_number             { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public string      c_surname              { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_first_name           { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_patronymic           { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public NpgsqlDate? d_birthday             { get; set; } // date
		[Column(SkipOnUpdate=true), Nullable] public string      address_reg1           { get; set; } // character varying(512)
		[Column(SkipOnUpdate=true), Nullable] public string      doc                    { get; set; } // text
		[Column(SkipOnUpdate=true), Nullable] public string      address_reg2           { get; set; } // character varying(512)
		[Column(SkipOnUpdate=true), Nullable] public string      pers_status            { get; set; } // text
		[Column(SkipOnUpdate=true), Nullable] public string      c_number               { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string      status_case            { get; set; } // character varying
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   death_date             { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   certificate_issue_date { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string      certificate_serial     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string      certificate_number     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public int?        f_org                  { get; set; } // integer
		[Column(SkipOnUpdate=true), Nullable] public string      c_type                 { get; set; } // text
	}

	[Table(Schema="fatalzp", Name="sv_cd_umer_pension", IsView=true)]
	public partial class fatalzp_sv_cd_umer_pension
	{
		[Column(SkipOnUpdate=true), Nullable] public long?       row_number      { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public string      c_surname       { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_first_name    { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_patronymic    { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public NpgsqlDate? d_birthday      { get; set; } // date
		[Column(SkipOnUpdate=true), Nullable] public string      c_number        { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public int?        f_status        { get; set; } // integer
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   ДатаСмертКаленд { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   ДатаВыдСвидет   { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string      СерияСвидет     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string      НомерСвидет     { get; set; } // character varying(8)
	}

	[Table(Schema="fatalzp", Name="sv_cd_umer_poor", IsView=true)]
	public partial class fatalzp_sv_cd_umer_poor
	{
		[Column(SkipOnUpdate=true), Nullable] public long?       row_number             { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public string      c_surname              { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_first_name           { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_patronymic           { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public NpgsqlDate? d_birthday             { get; set; } // date
		[Column(SkipOnUpdate=true), Nullable] public string      address_reg1           { get; set; } // character varying(512)
		[Column(SkipOnUpdate=true), Nullable] public string      doc                    { get; set; } // text
		[Column(SkipOnUpdate=true), Nullable] public string      address_reg2           { get; set; } // character varying(512)
		[Column(SkipOnUpdate=true), Nullable] public string      pers_status            { get; set; } // text
		[Column(SkipOnUpdate=true), Nullable] public string      c_number               { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string      status_case            { get; set; } // character varying(100)
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   death_date             { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   certificate_issue_date { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string      certificate_serial     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string      certificate_number     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public int?        f_org                  { get; set; } // integer
	}

	[Table(Schema="fatalzp", Name="sv_cd_umer_subsidy", IsView=true)]
	public partial class fatalzp_sv_cd_umer_subsidy
	{
		[Column(SkipOnUpdate=true), Nullable] public long?       row_number      { get; set; } // bigint
		[Column(SkipOnUpdate=true), Nullable] public string      c_surname       { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_first_name    { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      c_patronymic    { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public NpgsqlDate? d_birthday      { get; set; } // date
		[Column(SkipOnUpdate=true), Nullable] public string      address_reg1    { get; set; } // character varying(512)
		[Column(SkipOnUpdate=true), Nullable] public string      doc             { get; set; } // text
		[Column(SkipOnUpdate=true), Nullable] public string      address_reg2    { get; set; } // character varying(512)
		[Column(SkipOnUpdate=true), Nullable] public string      pers_status     { get; set; } // text
		[Column(SkipOnUpdate=true), Nullable] public string      c_number        { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string      status_case     { get; set; } // character varying(64)
		[Column(SkipOnUpdate=true), Nullable] public string      payment_method  { get; set; } // character varying(128)
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   ДатаСмертКаленд { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public DateTime?   ДатаВыдСвидет   { get; set; } // timestamp (6) without time zone
		[Column(SkipOnUpdate=true), Nullable] public string      СерияСвидет     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public string      НомерСвидет     { get; set; } // character varying(8)
		[Column(SkipOnUpdate=true), Nullable] public int?        f_org           { get; set; } // integer
	}

	[Table(Schema="sozags", Name="СОЗАГС_1")]
	public partial class sozags_СОЗАГС_1
	{
		[PrimaryKey, NotNull    ] public Guid      Id                                     { get; set; } // uuid
		[Column,        Nullable] public string    Код_органа_ЗАГС                        { get; set; } // text
		[Column,        Nullable] public string    Наименование_органа_ЗАГС               { get; set; } // text
		[Column,        Nullable] public string    Код_правоприемника                     { get; set; } // text
		[Column,        Nullable] public string    Код_вышестоящего_органа                { get; set; } // text
		[Column,        Nullable] public string    Код_органа_ЗАГС_хранения_запи_6EF73C16 { get; set; } // text
		[Column,        Nullable] public bool?     Признак_выполнения_функции_р_551855EA  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_р_9EC47360  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_р_B65D6F23  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_р_AB8F2E4D  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_р_FBB30CC2  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_р_176C3110  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_р_17346FE4  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_п_2D1A4123  { get; set; } // boolean
		[Column,        Nullable] public bool?     Признак_выполнения_функции_п_E2EEFEA7  { get; set; } // boolean
		[Column,        Nullable] public string    ОКТМО_обслуживаемой_территории         { get; set; } // text
		[Column,        Nullable] public string    Правоустанавливающие_докуме_E7E346A8   { get; set; } // text
		[Column,        Nullable] public string    ИНН                                    { get; set; } // text
		[Column,        Nullable] public string    ОГРН                                   { get; set; } // text
		[Column,        Nullable] public string    Адрес                                  { get; set; } // text
		[Column,        Nullable] public string    Телефон                                { get; set; } // text
		[Column,        Nullable] public string    Адрес_абонента_электронной_почты       { get; set; } // text
		[Column,        Nullable] public string    Адрес_сайта_в_сети_ИНТЕРНЕТ            { get; set; } // text
		[Column,        Nullable] public DateTime? Дата_начала_действия_записи            { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public DateTime? Дата_окончания_действия_записи         { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    Примечание                             { get; set; } // text
		[Column,        Nullable] public string    Часовая_зона                           { get; set; } // text
		[Column,        Nullable] public string    Разница_с_московским_временем          { get; set; } // text
		[Column,        Nullable] public string    UTC                                    { get; set; } // text
		[Column,        Nullable] public Guid?     Вид_органа                             { get; set; } // uuid

		#region Associations

		/// <summary>
		/// FK_sozags_СОЗАГС_1_Вид_органа_01289DF2
		/// </summary>
		[Association(ThisKey="Вид_органа", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_sozags_СОЗАГС_1_Вид_органа_01289DF2")]
		public sozags_СОЗАГС_1В СОЗАГС1Видоргана01289DF { get; set; }

		#endregion
	}

	[Table(Schema="sozags", Name="СОЗАГС_1В")]
	public partial class sozags_СОЗАГС_1В
	{
		[PrimaryKey, NotNull    ] public Guid   Id                       { get; set; } // uuid
		[Column,        Nullable] public string Код_вида_органа          { get; set; } // text
		[Column,        Nullable] public string Наименование_вида_органа { get; set; } // text
	}

	[Table(Schema="zags", Name="ОКСМ")]
	public partial class zags_ОКСМ
	{
		[PrimaryKey, NotNull    ] public Guid      Id                         { get; set; } // uuid
		[Column,        Nullable] public string    Цифровой_код               { get; set; } // character varying(3)
		[Column,        Nullable] public string    Краткое_наименование       { get; set; } // character varying(100)
		[Column,        Nullable] public string    Полное_наименование        { get; set; } // character varying(250)
		[Column,        Nullable] public string    Буквенный_код_альфа_2      { get; set; } // character varying(2)
		[Column,        Nullable] public string    Буквенный_код_альфа_3      { get; set; } // character varying(3)
		[Column,        Nullable] public string    Описание__пояснение_       { get; set; } // text
		[Column,        Nullable] public string    Номер_последнего_изменения { get; set; } // character varying(3)
		[Column,        Nullable] public int?      Тип_последнего_изменения   { get; set; } // integer
		[Column,        Nullable] public DateTime? Дата_принятия_изменения    { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public DateTime? Дата_введения_изменения    { get; set; } // timestamp (6) without time zone
	}

	[Table(Schema="zags", Name="СВЗАГС")]
	public partial class zags_СВЗАГС
	{
		[PrimaryKey, NotNull    ] public Guid      Id           { get; set; } // uuid
		[Column,        Nullable] public string    Код          { get; set; } // text
		[Column,        Nullable] public string    Наименование { get; set; } // text
		[Column,        Nullable] public DateTime? Дата_начала  { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    Примечание   { get; set; } // text
	}

	[Table(Schema="zags", Name="СДРАГС")]
	public partial class zags_СДРАГС
	{
		[PrimaryKey, NotNull    ] public Guid      Id                                   { get; set; } // uuid
		[Column,        Nullable] public string    Код                                  { get; set; } // text
		[Column,        Nullable] public string    Наименование_соответствующе_1179F532 { get; set; } // text
		[Column,        Nullable] public DateTime? Дата_начала                          { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    Примечание                           { get; set; } // text
	}

	[Table(Schema="zags", Name="СПДУЛ")]
	public partial class zags_СПДУЛ
	{
		[PrimaryKey, NotNull    ] public Guid   Id                     { get; set; } // uuid
		[Column,        Nullable] public string Код_документа          { get; set; } // character varying(2)
		[Column,        Nullable] public string Наименование_документа { get; set; } // character varying(75)
		[Column,        Nullable] public string Краткое_наименование   { get; set; } // character varying(6)
		[Column,        Nullable] public string Шаблон_серии_и_номера  { get; set; } // character varying(25)
		[Column,        Nullable] public string Примечание             { get; set; } // character varying(250)
	}

	[Table(Schema="zags", Name="СТАГС")]
	public partial class zags_СТАГС
	{
		[PrimaryKey, NotNull    ] public Guid      Id                      { get; set; } // uuid
		[Column,        Nullable] public string    Код                     { get; set; } // text
		[Column,        Nullable] public string    Наименование            { get; set; } // text
		[Column,        Nullable] public DateTime? Дата_начала_действия    { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public DateTime? Дата_окончания_действия { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string    Примечание              { get; set; } // text
	}
}

#pragma warning restore 1591
